# Generated by Django 5.2.4 on 2025-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedstorelist",
            name="is_user_defined",
            field=models.BooleanField(default=False),
        ),
    ]
