# Generated by Django 5.2.4 on 2025-10-22 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(default="Unnamed Cart", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="users.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "unique_together": {("cart", "product")},
            },
        ),
        migrations.CreateModel(
            name="SelectedStoreList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(default="My Store List", max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stores",
                    models.ManyToManyField(
                        related_name="store_lists", to="companies.store"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Selected Store List",
                "verbose_name_plural": "Selected Store Lists",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="cart",
            name="selected_store_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="users.selectedstorelist",
            ),
        ),
        migrations.CreateModel(
            name="CartSubstitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_cart_item",
                    models.ForeignKey(
                        help_text="The CartItem that this substitution is replacing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chosen_substitutions",
                        to="users.cartitem",
                    ),
                ),
                (
                    "substituted_product",
                    models.ForeignKey(
                        help_text="The actual substitute product chosen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutes_chosen_for_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Substitution",
                "verbose_name_plural": "Cart Substitutions",
                "unique_together": {("original_cart_item", "substituted_product")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "name")},
        ),
    ]
