# Generated by Django 5.2.4 on 2025-10-22 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_cart_cartitem_selectedstorelist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectedstorelist",
            name="is_default",
        ),
        migrations.AddField(
            model_name="selectedstorelist",
            name="last_used_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
