# Generated by Django 5.2.4 on 2025-10-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_cart_unique_together_cart_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartsubstitution",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
