# Generated by Django 5.2.4 on 2025-09-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={},
        ),
        migrations.RemoveField(
            model_name="price",
            name="scraped_at",
        ),
        migrations.AddField(
            model_name="price",
            name="scraped_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
