BRAND_SYNONYMS = {
    "25 degrees south": "25 degrees",
    "4 pines": "4 pines brewing",
    "abbott's": "Abbott's Bakery",
    "a2 the a2 milk company": "A2",
    "aeroplane": "Aeroplane Jelly",
    "arizona": "Arizona Iced Tea",
    "armor": "Armor All",
    "bic kids couleur": "BIC",
    "barossa": "Barossa Fine Foods",
    "Barossa Valley Cheese": "Barossa Valley Cheese Co",
    "beechworth honey": "Beechworth",
    "beerenberg dressing": "Beerenberg",
    "ben's original rice": "Ben's Original",
    "berocca hydrate": "Berocca",
    "Bibigo Korean Sytle": "bibigo korean",
    "bickfords cordial": "Bickford's",
    "bickfords iced mocha": "Bickford's",
    "bickfords pineapple": "Bickford's",
    "bickfords soda": "Bickford's",
    "biozet attack": "Biozet",
    "bonds flex leggings": "Bonds",
    "bonds men's": "Bonds",
    "bonds mens explorer socks": "Bonds",
    "bonds mens quarter crew": "Bonds",
    "bonds women's logo": "Bonds",
    "bonds womens seamless": "Bonds",
    "boost": "Boost Juice",
    "Brite Blonde": "Brite",
    "the british sausage co.": "British Sausage Co.",
    "brownes chill": "Brownes",
    "brownes dairy": "Brownes",
    "buderim": "Buderim Ginger",
    "Bundaberg Sugar": "Bundaberg",
    "burt's": "Burt's Bees",
    "byron": "Byron Beef Jerky",
    "Cadbury Buzz Bar": "Cadbury",
    "Calypso Lemonade": "Calypso",
    "campbell's v8": "Campbell's",
    "carlton zero": "Carlton",
    "carman's protein bars": "Carman's",
    "carmans nut bar slice": "Carman's",
    "celestial": "Celestial Seasonings",
    "ceres": "Ceres Organic",
    "ceres": "Ceres Organics",
    "clearblue early.": "Clearblue",
    "cobram": "Cobram Estate",
    "cocobella protein": "Cocobella",
    "cold power laundry liquid": "Cold Power",
    "Coles Finest": "Coles",
    "Coles Simply": "Coles",
    "coles bake at home": "Coles",
    "coles black forest": "Coles",
    "coles cocktail": "Coles",
    "coles dairy": "Coles",
    "coles facial tissues": "Coles",
    "coles finest provolone": "Coles",
    "coles fresh": "Coles",
    "coles happy birthday.": "Coles",
    "coles juice": "Coles",
    "coles kitchen": "Coles",
    "coles lamb boneless": "Coles",
    "coles large": "Coles",
    "coles lemon meringue tart": "Coles",
    "coles made easy": "Coles",
    "coles pineapple pieces": "Coles",
    "coles pineapple slices": "Coles",
    "coles pork ribs sticky": "Coles",
    "coles pro": "Coles",
    "coles rainbow bunting.": "Coles",
    "coles red velvet": "Coles",
    "coles round happy.": "Coles",
    "coles squeezy manuka": "Coles",
    "coles star decorations.": "Coles",
    "cycle by coles": "Coles",
    "coles finest provolone": "Coles Finest",
    "coopers ultra light": "Coopers",
    "cucina matese ita": "Cucina Matese",
    "darrell lea milk choc": "Darrell Lea",
    "Decor Vent & Seal": "Decor",
    "decor microsafe 3 in 1": "Decor",
    "decor microsafe rice": "Decor",
    "decor tellfresh": "Decor",
    "Decor Tellfresh Container": "decor tellfresh",
    "deep": "Deep Heat",
    "Disney Princess": "disney",
    "duracell everyday": "Duracell",
    "Eazii Mini Egg": "Eazii Mini",
    "El-amin's Beef": "el-amin's",
    "Fairy Platinum": "Fairy",
    "Fairy Platinum Plus": "Fairy",
    "Fairy Platinum Plus": "Fairy Platinum",
    "fanta flavours": "Fanta",
    "farmers union est 1888": "Farmers Union",
    "ferrero": "Ferrero Rocher",
    "fettayleh foods": "Fettayleh",
    "First Press Coffee": "First Press",
    "flora proactiv margarine": "Flora",
    "Garnier Olia Hair Colour": "GARNIER",
    "garnier pro retinol": "GARNIER",
    "Gatorade G X AFL Bottle": "Gatorade",
    "gem fragrance mist": "Gem",
    "gem skin loving deodorant": "Gem",
    "king c gillette": "Gillette",
    "glen": "Glen 20",
    "glen 20 scentsations": "Glen 20",
    "Glico Pocky": "Glico",
    "pocky": "Glico Pocky",
    "golden days sesame bites": "Golden Days",
    "great northern": "Great Northern Brewing Co.",
    "grenade high protein bar": "Grenade",
    "grinders cafe": "Grinders",
    "Guzzis Special Selection": "guzzi's",
    "haday superior": "Haday",
    "happy cake": "Happy Cake Co",
    "the happy cake co": "Happy Cake Co",
    "Harvey Beef": "Harvey",
    "Harvey Fresh": "Harvey",
    "health lab choc brownie": "Health Lab",
    "health lab cookie dough": "Health Lab",
    "health lab cookies 'n'": "Health Lab",
    "health lab cookies no": "Health Lab",
    "health lab pro ball chewy": "Health Lab",
    "health lab salted caramel": "Health Lab",
    "hellmann's real": "Hellmann's",
    "Herbal Essences": "Herbal",
    "Hunt And Brew": "Hunt & Brew",
    "hunt and brew extra": "Hunt & Brew",
    "hunt and brew extra": "Hunt And Brew",
    "iga fresh": "IGA",
    "impressed pressed juice": "Impressed",
    "indomie chitato": "Indomie",
    "Johnson's Baby": "Johnson's",
    "Jolly Rancher Hard": "Jolly Rancher",
    "jurassic world": "Jurassic",
    "just for men hair": "Just For Men",
    "Kinder Bueno": "Kinder",
    "kurrajong kitchen": "Kurrajong",
    "L'oreal Excellence": "L'Oreal",
    "l'oreal elvive hyaluron": "L'Oreal",
    "l'oreal telescopic": "L'Oreal",
    "lacura beauty": "LACURA",
    "latina": "Latina Fresh",
    "lee kum kee asian": "Lee Kum Kee",
    "lee kum kee powder": "Lee Kum Kee",
    "lindt lindor raspberry &": "Lindt",
    "lindt lindor tablet": "Lindt",
    "lotus biscoff": "Lotus",
    "lotus peak": "Lotus",
    "Lucia's Fine Foods": "Lucia's",
    "pods mars": "MARS",
    "macy & tailor pretzel": "Macy & Tailor",
    "macy and tailor": "Macy & Tailor",
    "Maggie Beer": "maggie",
    "Maybelline Great Lash": "Maybelline",
    "maybelline age rewind": "Maybelline",
    "maybelline expression": "Maybelline",
    "maybelline fit me": "Maybelline",
    "maybelline fit me d+s": "Maybelline",
    "maybelline fit me m+p": "Maybelline",
    "maybelline hypereasy": "Maybelline",
    "maybelline lifter gloss": "Maybelline",
    "maybelline superstay mi": "Maybelline",
    "maybelline tattoo studio": "Maybelline",
    "Meredith": "Meredith Dairy",
    "Mike and Ike": "Mike & Ike",
    "monster energy": "Monster",
    "monster energy can": "Monster",
    "Mother Energy": "Mother",
    "Mr Beast Feastables": "Mr. Beast",
    "musashi plant protein": "Musashi",
    "mutti sugo semplice": "Mutti",
    "nippy's juice": "Nippy's",
    "nippy's orange juice": "Nippy's",
    "nippys bottle dairy": "Nippy's",
    "oakwood shoe and boot": "Oakwood",
    "oates earthly": "Oates",
    "El- Amin's Halal": "El- Amin's",
    "olay complete+ rich": "Olay",
    "olay complete+ sensitive": "Olay",
    "optimum adult": "Optimum",
    "original juice": "Original Juice Co.",
    "outdoor life": "Outdoor",
    "oxyshred": "OxyShred Energy",
    "pana organic chai": "Pana Organic",
    "pauls plus": "Pauls",
    "pedigree dentastix": "Pedigree",
    "pepsi max": "Pepsi",
    "perfect italiano cheese": "Perfect Italiano",
    "piksters eco": "Piksters",
    "Pilbara Bakehouse White": "Pilbara Bakehouse",
    "pilot frixion clicker": "Pilot Frixion",
    "pods snickers": "Pods",
    "pods twix": "Pods",
    "praise squeeze": "Praise",
    "princi smallgoods": "Princi",
    "pump water": "Pump",
    "pureharvest barista": "PureHarvest",
    "purina one": "Purina",
    "purina total care": "Purina",
    "que cola": "Que",
    "queen victoria tea": "Queen Victoria",
    "red rock deli chips": "Red Rock Deli",
    "revlon colorstay n/d": "Revlon",
    "revlon super lustrous": "Revlon",
    "rimmel lasting finish": "Rimmel",
    "rimmel multi tasker": "Rimmel",
    "ritz breakz": "Ritz",
    "ritz snackz": "Ritz",
    "riviera bakery": "Riviera",
    "spc fruit snack fruit": "SPC",
    "sard wonder": "Sard",
    "schwarzkopf ultra brights": "Schwarzkopf",
    "schweppes infused": "Schweppes",
    "Sharpie Clear View": "Sharpie",
    "sharpie creative": "Sharpie",
    "simply wize gluten free": "Simply Wize",
    "sistema nest it meal prep": "Sistema",
    "Slape And Sons": "Slape & Sons",
    "smith's crackers": "Smith's",
    "smiths crinkle": "Smith's",
    "pods snickers": "Snickers",
    "Sour Patch": "sour patch kids",
    "Steggles Mini": "Steggles",
    "Sukin Botanical Body Wash": "Sukin",
    "sukin aquaboost 3d": "Sukin",
    "Sunrice Microwave": "SunRice",
    "Swisse Beauty": "Swisse",
    "takis blue": "Takis",
    "takis fuego": "Takis",
    "Tamar Valley Dairy": "Tamar Valley",
    "Tefal Cook Right Non": "Tefal",
    "tefal cook right": "Tefal",
    "tefal cook right xl non": "Tefal",
    "tefal so'light induction": "Tefal",
    "tefal cook right": "Tefal Cook Right Non",
    "tefal cook right xl non": "Tefal Cook Right Non",
    "Ultralife 55+": "Ultralife",
    "ultralife high strength": "Ultralife",
    "ultralife magnesium": "Ultralife",
    "ultralife mens": "Ultralife",
    "ultralife vitamin b3": "Ultralife",
    "ultralife vitamin d": "Ultralife",
    "ultralife womens": "Ultralife",
    "V Energy": "V",
    "Voost Hydrate": "VOOST",
    "voost plus": "VOOST",
    "wicked sister fine foods": "Wicked Sister",
    "wicked sister high": "Wicked Sister",
    "willy wonka": "Wonka",
    "Woofin Good Dog Food": "Woofin Good",
    "woofin good puppy df": "Woofin Good",
    "youfoodz fueld": "YouFoodz",
    "ak annabel karmel": "annabel karmel",
    "alcafe gold": "alcafe",
    "australian botanical bar soap": "australian botanical",
    "australian botanical soap": "australian botanical",
    "australian botanical soap": "australian botanical bar soap",
    "coloxyl with senna": "coloxyl",
    "cook & dine clip top jar": "cook & dine",
    "cook & dine contemporary": "cook & dine",
    "cook & dine novelty mug": "cook & dine",
    "cook & dine tall tumblers": "cook & dine",
    "cook & dine terry tea": "cook & dine",
    "cook & dine trend mug": "cook & dine",
    "deli originals fresh": "deli originals",
    "dolmio extra pasta sauce": "dolmio",
    "grisbi filled biscuits": "grisbi biscuits",
    "the happy snack company": "happy snack company",
    "haribo bags": "haribo",
    "herman brot lower carb": "herman brot",
    "hi fresh salads": "hi fresh",
    "hot topic licensed mug": "hot topic",
    "jade phoenix shitake": "jade phoenix",
    "palm": "jeeny's palm",
    "kewpie japanese dressing": "kewpie",
    "kirin hyoketsu": "kirin",
    "lo bros up berry": "lo bros up",
    "maharajah's choice large": "maharajah's choice",
    "muscle nation papi pro": "muscle nation",
    "natural cracker co": "the natural cracker co.",
    "nong shim shin ramyun": "nong shim",
    "paolo's artisan": "paolo's artisan bakery",
    "paw grocer": "the paw grocer",
    "pyrex bake n serve glass": "pyrex",
    "pyrex bake n store glass": "pyrex",
    "razza matazz": "razza",
    "red rock deli chips": "red rock",
    "republica organic": "republica",
    "rodara screwdriver set": "rodara",
    "run free by singlefile": "singlefile",
    "s&b curry sauce": "s&b",
    "slice x chupa balls": "slice x",
    "squid brand sauce": "squid brand",
    "squisito pasta": "squisito",
    "sundae  for kids": "sundae for kids",
    "suntory boss coffee": "suntory",
    "suntory toki": "suntory",
    "systane ultra": "systane",
    "tablelands dairy blend": "tablelands",
    "tandil ultra": "tandil",
    "tefal cook right xl non": "tefal cook right",
    "the honey collective": "the honey collective co",
    "the maple treat": "the maple treat corp",
    "touchbio home": "touchbio",
    "wai wai rice": "wai wai",
    "yeo's satay": "yeo's",
    "zantac double": "zantac",
    "melrose peak hydrations": "melrose peak hydration",
    "pana organics": "Pana Organic",
    "fisher-price": "fisher price",
    "microprotect": "micro protect",
    "catalano'ss": "Catalano's",
    "chickeadees": "Chickadees",
    "David Gray": "david grays",
    "Fever-Tree": "Fever Tree",
    "Greenleaf": "Green Leaf",
    "life saver": "Life Savers",
    "lifesavers": "Life Savers",
    "lifestyle": "LifeStyles",
    "soda stream": "Sodastream",
    "brittannia": "britannia",
    "brittania value pack": "britannia  value pack",
    "clearwipes": "clearwipe",
    "dairyfine": "dairy fine",
    "gastro-stop": "gastro stop",
    "lifesaver": "lifesavers",
    "miirabella": "mirabella",
    "mr brownies": "mr brownie",
    "pot noodles": "pot noodle",
    "brunsick": "Brunswick",
    "COCA-COLA": "Coca Cola",
    "Cca Cola": "Coca Cola",
    "liddellls": "Liddells",
    "Magazine": "magazines",
    "strepsil": "Strepsils",
    "babushka": "babushka's",
    "beach rd naturals": "beach road naturals",
    "fun fave": "fun faves",
    "hengshun": "heng shun",
    "lumi skin": "lumiskin",
    "nongshim": "nong shim",
    "rowntrees": "rowntree",
    "easy off": "Easy-Off",
    "papa guiseppi's": "Papa Giuseppi's",
    "TRESemme": "TRESemmé",
    "Warhead": "Warheads",
    "bun plus": "bun-plus",
    "double pheonix": "double phoenix",
    "ipastai": "i pastai",
    "joo joos": "joojoos",
    "kantong": "kan tong",
    "palirra": "palirria",
    "salt & co": "salts & co",
    "wescott": "westcott",
    "ingham": "Ingham's",
    "marc daneils": "Marc Daniels",
    "sellys": "Selleys",
    "kook 'a' crumb": "kook a krumb",
    "parker": "parker's",
    "ajitas": "Ajita",
    "finsh": "Finish",
    "gullon": "Gullón",
    "Iki- Na": "Iki-Na",
    "John Freida": "John Frieda",
    "Nestle": "Nestlé",
    "de gas": "de-gas",
    "kuhne": "kuehne",
    "the natural chip company": "the natural chip co.",
    "lifesaver": "Life Savers",
    "coco & lucus": "coco & lucas",
    "life saver": "lifesavers",
    "5Gum": "5 gum",
    "k roo": "K-Roo",
    "Soul Mare": "Sole Mare",
    "caves rd": "caves road",
    "natural chip co": "the natural chip company",
    "olga": "olga's",
    "rowntress": "rowntrees",
    "4 Seasons": "Four Seasons",
    "Cca Cola": "COCA-COLA",
    "Mt. Franklin": "Mount Franklin",
    "sam remo": "San Remo",
    "the natural confect co.": "The Natural Confectionery Co.",
    "swizzles": "swizzels",
    "The Kimchi Co": "the kimchi company",
    "-196": "Suntory",
    "SUNTORY -196 C": "Suntory",
    "Ausfresh Green Olives": "Ausfresh",
    "Bondi Circus Oat": "bondi circus",
    "boulder canyon": "Boulder Canyon Chips",
    "boulder chips": "Boulder Canyon Chips",
    "CORONA EXTRA": "corona",
    "Ceres Organic Pea Chips": "Ceres Organic",
    "Ceres Organic Pea": "Ceres Organic",
    "Ceres Organic Pea Chips": "Ceres Organic",
    "Cleaver's Organic": "Cleaver's",
    "Dare Intense Espresso": "DARE",
    "double d smart sweets": "Double D",
    "Fortune Soy Tofu": "Fortune",
    "Glaceau Vitaminwater": "Glaceau",
    "Ice Break Triple Shot": "Ice Break",
    "ito en oi ocha": "Ito En",
    "kb's cooked": "KB's",
    "kb's spencer gulf thawed": "KB's",
    "kb's thawed": "KB's",
    "kb's thawed atlantic": "KB's",
    "kb's thawed cooked": "KB's",
    "kb's thawed raw": "KB's",
    "kb's thawed seafood": "KB's",
    "msc kb's": "KB's",
    "Killer Coffee Co": "The Killer Coffee Co.",
    "molisana": "La Molisana Pasta",
    "Mountain Dew": "Schweppes",
    "Schweppes Mountain Dew": "Schweppes",
    "muscle nation crisp bar": "Muscle Nation",
    "muscle nation daily shake": "Muscle Nation",
    "Olina's Bakehouse Bakehouse": "olina's bakehouse",
    "Onkaparinga": "Onkaparinga Creamery",
    "power force pro": "POWER FORCE",
    "Paldo": "paldo dosirac",
    "Pat & Stick's": "Pat And Stick's",
    "Proper Crisps Potato Big": "Proper Crisps",
    "Proper Crisps Potato": "Proper Crisps",
    "Proper Crisps Potato Big": "Proper Crisps",
    "Pryme Wagyu Beef": "Pryme",
    "Sellotape Removable": "Sellotape",
    "Strangelove Tangerine": "Strangelove",
    "Strangelove Yuzu": "Strangelove",
    "Sunfeast Dark Fantasy": "sunfeast",
    "pure produce company": "The Pure Produce Company",
    "The Vegan Dairy Aged": "The Vegan Dairy",
    "The Vegan Dairy Herb": "The Vegan Dairy",
    "la casa del formagio": "la casa del formaggio",
    "lvl up everday": "Lvl Up Everyday",
    "fromager d'affiniois": "fromager d'affinois",
    "coes kitchen": "Coles Kitchen",
    "harvest snap": "Harvest Snaps",
    "kooka a krumb": "Kook A Krumb",
    "little tree": "Little Trees",
    "messy monkey": "Messy Monkeys",
    "ching secret": "chings secret",
    "mcilhenney co": "mcilhenny co",
    "Britannia  Value Pack": "Brittania Value Pack",
    "deruiter": "De Ruiter",
    "Damp Rid": "DampRid",
    "damprid": "DampRid",
    "Hot Kid": "Want Want",
    "hot kids": "Want Want",
    "Ingham": "INGHAM'S",
    "Cremorne St Bakers": "Cremorne Street Bakers",
    "heidi": "Heidis",
    "Byron Bay Cookie Co": "Byron Bay Cookie Company",
    "Byron Bay Cookies": "Byron Bay Cookie Company",
    "MT Barker": "Mount Barker",
    "The Vegan Dairy Aged": "The Vegan Dairy",
    "The Vegan Dairy Herb": "The Vegan Dairy",
    "Linda McCartney": "Linda Mccartney's",
    "Mama Rosa's Kitchen": "Mamma Rosa's Kitchen",
    "Uncle Smallgoods": "Uncle's Smallgoods",
    "Clearwipes": "Clearwipe",
    "Kozhikoden": "Kozhikoden's",
    "symintons": "Symington's",
    "guerrerro": "Guerrero",
    "Floridia": "Florida",
    "Nautropathica": "Naturopathica",
    "Daily Juice": "Daily Juice Company",
    "Daily Juice Co": "Daily Juice Company",
    "rutherford & meyer": "Rutherford and Meyer",
    "tegels": "Tegel",
    "Cheesecake Shop": "The Cheesecake Shop",
    "Jinmailing": "Jinmailang",
    "Mrs H S Balls": "Mrs H.S. Ball's",
    "Only Juice Co.": "Only Juice",
    "juice brothers": "The Juice Brothers",
    "Miirabella": "Mirabella",
    "moet & chandon": "Moët & Chandon",
    "Mt Difficulty": "Mount Difficulty",
    "Rowntress": "Rowntree's",
    "Soul Papa": "soul papa & co",
    "healthy baker": "The Healthy Baker",
    "Laughing Cow": "The Laughing Cow",
    "Sea Friend": "friends",
    "Starward": "star wars",
    "Swizzles": "Swizzels",
    "Black & White": "black and white",
    "Shaw & Smith": "shaw and smith",
    "singleton": "The Singleton",
    "HB": "HB Belly Me",
    "hb belly": "HB Belly Me",
    "marion's": "Marion's Kitchen",
    "pilot frixon": "Pilot",
    "primo reserve": "Primo",
    "schick intuition": "Schick",
    "Twisted": "Twisted Healthy Treats",
    "twisted frozen yoghurt": "Twisted Healthy Treats",
    "Twisted": "twisted healthy treats",
    "carob kitchen": "the carob kitchen",
    "damora satisfied snacking": "damora",
    "e.l.f. poreless": "e.l.f.",
    "logix platinum": "logix",
    "monini basil pesto": "monini",
    "monini vegan basil pesto": "monini",
    "mum dry": "mum",
    "nice rice australian": "nice rice",
    "oxfam": "fair coffee",
    "oxfam fair": "fair coffee",
    "riviana risotto": "riviana",
    "snackify yoghurt": "snackify",
    "so soft": "so soft marshmallow co",
    "suimin origins": "suimin",
    "sup shred": "sup",
    "tbh patch it up": "tbh",
    "tbh rebound": "tbh",
    "ted baker london": "ted baker",
    "the hills cider company": "the hills",
    "tibaldi australian": "tibaldi",
    "truly hard": "truly",
    "v.i.p. petfoods": "v.i.p",
    "v2 burger beef": "v2",
    "westacre": "westacre dairy",
    "oh so natural superfoods": "oh so natural foods",
    "oh so natural wholefoods": "oh so natural foods",
    "U/works Kids School Socks": "underworks",
    "u/works kids sport socks": "underworks",
    "BOMBAY SAPPHIRE": "bombay",
    "Capi Tonic Water": "Capi",
    "Careme Pastry": "Careme",
    "Clif Builders": "Clif",
    "Cosmic Sour": "Cosmic",
    "GRANDESSA RESERVE": "grandessa",
    "Guzzi's Free Range": "Guzzi's",
    "ines rosa": "Ines",
    "Inglewood Farms": "Inglewood",
    "Ivan's Aussie Family.": "Ivan's",
    "julius gold": "JULIUS",
    "Kushi Jelly Jar": "kushi",
    "Lyres Non Alc Spirit": "Lyre's",
    "MEB": "meb foods",
    "macro meats": "Macro",
    "maharajah's": "Maharajah's Choice",
    "Nomma Portobello &": "Nomma",
    "O'food Seaweed Chips": "O'FOOD",
    "Otway Pasta": "Otway Pasta Company",
    "RIVET GOLD": "RIVET",
    "Sartori Cherrywood": "Sartori",
    "Trill Vitablend Pellets": "Trill",
    "Vegan Life Non": "vegan life",
    "Vegan Life Non Dairy": "vegan life",
    "Vili's Family Bakery": "Vili's",
    "Vithit Health Drink": "Vithit",
    "WYNNS ESTATE": "Wynns",
    "cucina classica": "Cucina",
    "Woodside Patrice": "Woodside",
    "yacoya jellyb": "yacoya",
    "yopro": "danone",
    "daily juice": "daily juice co",
    "kellogg's": "kellogg’s",
    "nestle": "nestlé",
    "h2melon": "h2juice",
    "h2coco": "h2",
    "h2juice": "h2",
    "glick's": "glicks",
    "original juice co": "original juice co.",
    "up & go": "up&go",
    "arnotts": "arnott's",
    "blue ribbon": "streets",
    "viennetta": "streets",
    "so good": "sanitarium",
    "chris' dip": "chris'",
    "snowdonia cheese co": "snowdonia",
    "oatly!": "oatly",
    "pauls zymil": "pauls",
    "bel": "laughing cow",
    "a2 milk": "a2",
    "tamar valley": "tamar valley dairy",
    "my life": "bio cheese",
    "baby bellies": "little bellies",
    "bhuja": "majans",
    "infuzions": "majans",
    "harvest snaps": "calbee",
    "grain waves": "sunbites",
    "kooee": "kooee!",
    "pop box": "popbox",
    "goodness me": "goodnessme",
    "pumped": "pump",
    "bc": "bc snacks",
    "kinder bueno": "kinder",
    "pickers": "mccain",
    "chomp": "cadbury",
    "mr beast feastables": "mr beast",
    "scorched peanut": "cooks confectionery",
    "orion turtle": "orion",
    "polly waffle": "menz",
    "ferrero collection": "ferrero rocher",
    "double d": "double 'd'",
    "juicy fruit": "wrigley's",
    "anticol": "allens",
    "toobs": "tasty toobs",
    "mcvitie's": "mcvities",
    "kooka's country": "kooka's",
    "maltesers": "mars",
    "passage to thailand": "passage to asia",
    "coca cola": "coca-cola",
    "jacob's": "jacobs",
    "f. whitlock & sons": "f.whitlock & sons",
    "providore": "leggo's",
    "freedom": "freedom foods",
    "starbucks by nespresso": "starbucks",
    "pic's": "pics",
    "leatherwood": "r stephens",
    "t2 tea": "t2",
    "creative kitchen": "the creative kitchen",
    "cornwells": "cornwell's",
    "south australian gourmet food company": "sa gourmet food co.",
    "solemare": "sole mare",
    "ichiban delicious": "welih",
    "galaxy": "mars",
    "o'food": "ofood",
    "monster munch": "walkers",
    "sonora": "sonora foods",
    "mt. franklin": "mount franklin",
    "v energy": "v",
    "barnes & brown": "barnes and brown",
    "fever tree": "fever-tree",
    "passiona": "schweppes",
    "mother energy": "mother",
    "great northern brewing co.": "great northern brewing co",
    "wynns coonawarra estate": "wynns",
    "mcwilliam's wines": "mcwilliam's",
    "hawke's brewing co.": "hawke's brewing co",
    "1800 tequila": "1800",
    "calabria family wines": "calabria",
    "georg jensen hallmark": "georg jensen",
    "sierra tequila": "sierra",
    "kraken": "the kraken",
    "tresemme": "tresemmé",
    "burt's bees": "burts bees",
    "lucas'": "lucas' papaw remedies",
    "plunkett's pure aloe vera": "plunkett's",
    "l'oreal paris": "l'oréal",
    "l'oréal": "l'oreal",
    "napro": "napro palette",
    "thankyou": "thankyou.",
    "venus": "gillette",
    "organic care": "oc naturals",
    "pro:voke": "provoke",
    "toni&guy": "toni & guy",
    "imperial leather": "cussons",
    "bar counter": "the bar counter",
    "pana": "pana organic",
    "sweet william chocolate": "sweet william",
    "mentholatum": "deep heat",
    "4 seasons": "four seasons",
    "duro tuss": "duro-tuss",
    "durotuss": "duro-tuss",
    "ansell": "vileda",
    "selley's": "selleys",
    "botanica": "air wick",
    "liquid-plumr": "clorox",
    "cove": "earth choice",
    "scotchgard": "3m",
    "drano": "sc johnson",
    "mr muscle": "sc johnson",
    "drynites": "huggies",
    "bellamy's organic": "bellamy's",
    "nutricia": "karicare",
    "fancy feast": "purina",
    "breeder's choice": "breeders choice",
    "love 'em": "love'em",
    "world's best cat litter": "world's best",
    "felix": "purina",
    "friskies": "purina",
    "total care": "purina",
    "lucky dog": "purina",
    "supercoat": "purina",
    "footcare": "maseur",
    "hot hands": "hothands",
    "cleaver's organic": "cleaver's",
    "riverina": "the riverina dairy",
    "pure harvest": "pureharvest",
    "closer to nature": "tommee tippee",
}
