BRAND_SYNONYMS = {
    "25 degrees south": "25 degrees",
    "4 pines": "4 pines brewing",
    "abbott's": "Abbott's Bakery",
    "a2 the a2 milk company": "A2",
    "aeroplane": "Aeroplane Jelly",
    "arizona": "Arizona Iced Tea",
    "armor": "Armor All",
    "bic kids couleur": "BIC",
    "barossa": "Barossa Fine Foods",
    "Barossa Valley Cheese": "Barossa Valley Cheese Co",
    "beechworth honey": "Beechworth",
    "beerenberg dressing": "Beerenberg",
    "ben's original rice": "Ben's Original",
    "berocca hydrate": "Berocca",
    "Bibigo Korean Sytle": "bibigo korean",
    "bickfords cordial": "Bickford's",
    "bickfords iced mocha": "Bickford's",
    "bickfords pineapple": "Bickford's",
    "bickfords soda": "Bickford's",
    "biozet attack": "Biozet",
    "bonds flex leggings": "Bonds",
    "bonds men's": "Bonds",
    "bonds mens explorer socks": "Bonds",
    "bonds mens quarter crew": "Bonds",
    "bonds women's logo": "Bonds",
    "bonds womens seamless": "Bonds",
    "boost": "Boost Juice",
    "Brite Blonde": "Brite",
    "the british sausage co.": "British Sausage Co.",
    "brownes chill": "Brownes",
    "brownes dairy": "Brownes",
    "buderim": "Buderim Ginger",
    "Bundaberg Sugar": "Bundaberg",
    "burt's": "Burt's Bees",
    "byron": "Byron Beef Jerky",
    "Cadbury Buzz Bar": "Cadbury",
    "Calypso Lemonade": "Calypso",
    "campbell's v8": "Campbell's",
    "carlton zero": "Carlton",
    "carman's protein bars": "Carman's",
    "carmans nut bar slice": "Carman's",
    "celestial": "Celestial Seasonings",
    "ceres": "Ceres Organic",
    "ceres": "Ceres Organics",
    "clearblue early.": "Clearblue",
    "cobram": "Cobram Estate",
    "cocobella protein": "Cocobella",
    "cold power laundry liquid": "Cold Power",
    "Coles Finest": "Coles",
    "Coles Simply": "Coles",
    "coles bake at home": "Coles",
    "coles black forest": "Coles",
    "coles cocktail": "Coles",
    "coles dairy": "Coles",
    "coles facial tissues": "Coles",
    "coles finest provolone": "Coles",
    "coles fresh": "Coles",
    "coles happy birthday.": "Coles",
    "coles juice": "Coles",
    "coles kitchen": "Coles",
    "coles lamb boneless": "Coles",
    "coles large": "Coles",
    "coles lemon meringue tart": "Coles",
    "coles made easy": "Coles",
    "coles pineapple pieces": "Coles",
    "coles pineapple slices": "Coles",
    "coles pork ribs sticky": "Coles",
    "coles pro": "Coles",
    "coles rainbow bunting.": "Coles",
    "coles red velvet": "Coles",
    "coles round happy.": "Coles",
    "coles squeezy manuka": "Coles",
    "coles star decorations.": "Coles",
    "cycle by coles": "Coles",
    "coles finest provolone": "Coles Finest",
    "coopers ultra light": "Coopers",
    "cucina matese ita": "Cucina Matese",
    "darrell lea milk choc": "Darrell Lea",
    "Decor Vent & Seal": "Decor",
    "decor microsafe 3 in 1": "Decor",
    "decor microsafe rice": "Decor",
    "decor tellfresh": "Decor",
    "Decor Tellfresh Container": "decor tellfresh",
    "deep": "Deep Heat",
    "Disney Princess": "disney",
    "duracell everyday": "Duracell",
    "Eazii Mini Egg": "Eazii Mini",
    "El-amin's Beef": "el-amin's",
    "Fairy Platinum": "Fairy",
    "Fairy Platinum Plus": "Fairy",
    "Fairy Platinum Plus": "Fairy Platinum",
    "fanta flavours": "Fanta",
    "farmers union est 1888": "Farmers Union",
    "ferrero": "Ferrero Rocher",
    "fettayleh foods": "Fettayleh",
    "First Press Coffee": "First Press",
    "flora proactiv margarine": "Flora",
    "Garnier Olia Hair Colour": "GARNIER",
    "garnier pro retinol": "GARNIER",
    "Gatorade G X AFL Bottle": "Gatorade",
    "gem fragrance mist": "Gem",
    "gem skin loving deodorant": "Gem",
    "king c gillette": "Gillette",
    "glen": "Glen 20",
    "glen 20 scentsations": "Glen 20",
    "Glico Pocky": "Glico",
    "pocky": "Glico Pocky",
    "golden days sesame bites": "Golden Days",
    "great northern": "Great Northern Brewing Co.",
    "grenade high protein bar": "Grenade",
    "grinders cafe": "Grinders",
    "Guzzis Special Selection": "guzzi's",
    "haday superior": "Haday",
    "happy cake": "Happy Cake Co",
    "the happy cake co": "Happy Cake Co",
    "Harvey Beef": "Harvey",
    "Harvey Fresh": "Harvey",
    "health lab choc brownie": "Health Lab",
    "health lab cookie dough": "Health Lab",
    "health lab cookies 'n'": "Health Lab",
    "health lab cookies no": "Health Lab",
    "health lab pro ball chewy": "Health Lab",
    "health lab salted caramel": "Health Lab",
    "hellmann's real": "Hellmann's",
    "Herbal Essences": "Herbal",
    "Hunt And Brew": "Hunt & Brew",
    "hunt and brew extra": "Hunt & Brew",
    "hunt and brew extra": "Hunt And Brew",
    "iga fresh": "IGA",
    "impressed pressed juice": "Impressed",
    "indomie chitato": "Indomie",
    "Johnson's Baby": "Johnson's",
    "Jolly Rancher Hard": "Jolly Rancher",
    "jurassic world": "Jurassic",
    "just for men hair": "Just For Men",
    "Kinder Bueno": "Kinder",
    "kurrajong kitchen": "Kurrajong",
    "L'oreal Excellence": "L'Oreal",
    "l'oreal elvive hyaluron": "L'Oreal",
    "l'oreal telescopic": "L'Oreal",
    "lacura beauty": "LACURA",
    "latina": "Latina Fresh",
    "lee kum kee asian": "Lee Kum Kee",
    "lee kum kee powder": "Lee Kum Kee",
    "lindt lindor raspberry &": "Lindt",
    "lindt lindor tablet": "Lindt",
    "lotus biscoff": "Lotus",
    "lotus peak": "Lotus",
    "Lucia's Fine Foods": "Lucia's",
    "pods mars": "MARS",
    "macy & tailor pretzel": "Macy & Tailor",
    "macy and tailor": "Macy & Tailor",
    "Maggie Beer": "maggie",
    "Maybelline Great Lash": "Maybelline",
    "maybelline age rewind": "Maybelline",
    "maybelline expression": "Maybelline",
    "maybelline fit me": "Maybelline",
    "maybelline fit me d+s": "Maybelline",
    "maybelline fit me m+p": "Maybelline",
    "maybelline hypereasy": "Maybelline",
    "maybelline lifter gloss": "Maybelline",
    "maybelline superstay mi": "Maybelline",
    "maybelline tattoo studio": "Maybelline",
    "Meredith": "Meredith Dairy",
    "Mike and Ike": "Mike & Ike",
    "monster energy": "Monster",
    "monster energy can": "Monster",
    "Mother Energy": "Mother",
    "Mr Beast Feastables": "Mr. Beast",
    "musashi plant protein": "Musashi",
    "mutti sugo semplice": "Mutti",
    "nippy's juice": "Nippy's",
    "nippy's orange juice": "Nippy's",
    "nippys bottle dairy": "Nippy's",
    "oakwood shoe and boot": "Oakwood",
    "oates earthly": "Oates",
    "El- Amin's Halal": "El- Amin's",
    "olay complete+ rich": "Olay",
    "olay complete+ sensitive": "Olay",
    "optimum adult": "Optimum",
    "original juice": "Original Juice Co.",
    "outdoor life": "Outdoor",
    "oxyshred": "OxyShred Energy",
    "pana organic chai": "Pana Organic",
    "pauls plus": "Pauls",
    "pedigree dentastix": "Pedigree",
    "pepsi max": "Pepsi",
    "perfect italiano cheese": "Perfect Italiano",
    "piksters eco": "Piksters",
    "Pilbara Bakehouse White": "Pilbara Bakehouse",
    "pilot frixion clicker": "Pilot Frixion",
    "pods snickers": "Pods",
    "pods twix": "Pods",
    "praise squeeze": "Praise",
    "princi smallgoods": "Princi",
    "pump water": "Pump",
    "pureharvest barista": "PureHarvest",
    "purina one": "Purina",
    "purina total care": "Purina",
    "que cola": "Que",
    "queen victoria tea": "Queen Victoria",
    "red rock deli chips": "Red Rock Deli",
    "revlon colorstay n/d": "Revlon",
    "revlon super lustrous": "Revlon",
    "rimmel lasting finish": "Rimmel",
    "rimmel multi tasker": "Rimmel",
    "ritz breakz": "Ritz",
    "ritz snackz": "Ritz",
    "riviera bakery": "Riviera",
    "spc fruit snack fruit": "SPC",
    "sard wonder": "Sard",
    "schwarzkopf ultra brights": "Schwarzkopf",
    "schweppes infused": "Schweppes",
    "Sharpie Clear View": "Sharpie",
    "sharpie creative": "Sharpie",
    "simply wize gluten free": "Simply Wize",
    "sistema nest it meal prep": "Sistema",
    "Slape And Sons": "Slape & Sons",
    "smith's crackers": "Smith's",
    "smiths crinkle": "Smith's",
    "pods snickers": "Snickers",
    "Sour Patch": "sour patch kids",
    "Steggles Mini": "Steggles",
    "Sukin Botanical Body Wash": "Sukin",
    "sukin aquaboost 3d": "Sukin",
    "Sunrice Microwave": "SunRice",
    "Swisse Beauty": "Swisse",
    "takis blue": "Takis",
    "takis fuego": "Takis",
    "Tamar Valley Dairy": "Tamar Valley",
    "Tefal Cook Right Non": "Tefal",
    "tefal cook right": "Tefal",
    "tefal cook right xl non": "Tefal",
    "tefal so'light induction": "Tefal",
    "tefal cook right": "Tefal Cook Right Non",
    "tefal cook right xl non": "Tefal Cook Right Non",
    "Ultralife 55+": "Ultralife",
    "ultralife high strength": "Ultralife",
    "ultralife magnesium": "Ultralife",
    "ultralife mens": "Ultralife",
    "ultralife vitamin b3": "Ultralife",
    "ultralife vitamin d": "Ultralife",
    "ultralife womens": "Ultralife",
    "V Energy": "V",
    "Voost Hydrate": "VOOST",
    "voost plus": "VOOST",
    "wicked sister fine foods": "Wicked Sister",
    "wicked sister high": "Wicked Sister",
    "willy wonka": "Wonka",
    "Woofin Good Dog Food": "Woofin Good",
    "woofin good puppy df": "Woofin Good",
    "youfoodz fueld": "YouFoodz",
    "ak annabel karmel": "annabel karmel",
    "alcafe gold": "alcafe",
    "australian botanical bar soap": "australian botanical",
    "australian botanical soap": "australian botanical",
    "australian botanical soap": "australian botanical bar soap",
    "coloxyl with senna": "coloxyl",
    "cook & dine clip top jar": "cook & dine",
    "cook & dine contemporary": "cook & dine",
    "cook & dine novelty mug": "cook & dine",
    "cook & dine tall tumblers": "cook & dine",
    "cook & dine terry tea": "cook & dine",
    "cook & dine trend mug": "cook & dine",
    "deli originals fresh": "deli originals",
    "dolmio extra pasta sauce": "dolmio",
    "grisbi filled biscuits": "grisbi biscuits",
    "the happy snack company": "happy snack company",
    "haribo bags": "haribo",
    "herman brot lower carb": "herman brot",
    "hi fresh salads": "hi fresh",
    "hot topic licensed mug": "hot topic",
    "jade phoenix shitake": "jade phoenix",
    "palm": "jeeny's palm",
    "kewpie japanese dressing": "kewpie",
    "kirin hyoketsu": "kirin",
}
