CATEGORY_MAPPINGS = {   'Aldi': {   'Advent Calendars': None,
                'Air Fresheners & Fragrances': 'Cleaning',
                'Antipasto': 'Miscellaneous',
                'Baby': 'Baby',
                'Baby Food': 'Baby',
                'Baby Formula': 'Baby',
                'Baby Nappies & Wipes': 'Baby',
                'Bakery': 'Bakery',
                'Baking': 'Bakery',
                'Bathroom': 'Cleaning',
                'Beef': 'Meat',
                'Beer': 'Alcoholic Drinks',
                'Birds': 'Pet',
                'Biscuit & Cookies': 'Sweets',
                'Biscuits & Cookies': 'Sweets',
                'Butter & Margarine': 'Dairy',
                'Cakes, Puddings & Pies': 'Snacks',
                'Canned Food': 'Pantry',
                'Cat & Kitten': 'Pet',
                'Cereals & Muesli': 'Pantry',
                'Cheese': 'Dairy',
                'Chips & Wedges': 'Freezer',
                'Chips, Corn Chips & Other': 'Snacks',
                'Chocolate': 'Sweets',
                'Christmas': None,
                'Cider': 'Alcoholic Drinks',
                'Cleaning': 'Cleaning',
                'Cleaning & Home and Garden': 'Cleaning',
                'Cleaning & Household': 'Cleaning',
                'Collectables': None,
                'Condiments & Dressings': 'Sauces',
                'Confectionery': 'Sweets',
                'Cosmetics': 'Health and Beauty',
                'Crackers & Crisp Breads': 'Snacks',
                'Creams & Custards': 'Dairy',
                'Dairy, Eggs & Fridge': None,
                'Decorations': 'Home',
                'Deli & Chilled Meats': None,
                'Deli Meats': 'Meat',
                'Dental Care': 'Health and Beauty',
                'Desserts': 'Sweets',
                'Dips & Spreads': 'Snacks',
                'Dogs & Puppy': 'Pet',
                'Dried Fruits, Nuts & Jerky': 'Fruit',
                'Drinks': 'Alcoholic Drinks',
                'Eggs': 'Eggs',
                'First Aid & Medicinal': 'Health and Beauty',
                'Fish': 'Seafood',
                'Flavoured Milk': 'Sweets',
                'Flowers': None,
                'Freezer': 'Freezer',
                'Fresh Fruits': 'Fruit',
                'Fresh Herbs': 'Spices',
                'Fresh Vegetables': 'Veg',
                'Front Of Store': None,
                'Frozen Desserts': 'Freezer',
                'Frozen Fruit & Vegetables': 'Fruit',
                'Frozen Meat & Seafood': 'Miscellaneous',
                'Frozen Party Food': 'Freezer',
                'Frozen Party Food & Snacks': 'Snacks',
                'Frozen Pizzas': 'Freezer',
                'Frozen Ready Meals': 'Freezer',
                'Fruits & Vegetables': 'Fruit',
                'Gift Wrapping & Gifts': None,
                'Hair Care': 'Health and Beauty',
                'Hair Removal': 'Health and Beauty',
                'Health & Beauty': 'Health and Beauty',
                'Health Foods': 'Health and Beauty',
                'Herbs & Spices': 'Spices',
                'Home Essentials': 'Home',
                'Ice Cream Snacks': 'Freezer',
                'Ice Cream Tubs': 'Freezer',
                'Iced Tea & Kombucha': 'Health Foods',
                'Jams & Spreads': 'Pantry',
                'Juices & Cordials': 'Non-Alcoholic Drinks',
                'Kids Craft': None,
                'Kitchen': 'Home',
                'Kitchen & Tableware': 'Home',
                'Lamb': 'Meat',
                'Laundry': 'Cleaning',
                'Lighting': 'Home',
                'Limited Time Only': 'Deals',
                'Liquor': 'Alcoholic Drinks',
                'Liquor & Drinks': None,
                'Lollies & Sweets': 'Sweets',
                'Long Life Milk': 'Dairy',
                'Lunch Box': 'Miscellaneous',
                'Meal Kits': 'Deli',
                'Meat & Seafood': None,
                'Milk': 'Dairy',
                'Muffins, Cakes & Other': 'Sweets',
                'Nibbles': 'Snacks',
                'Oils & Vinegars': 'Pantry',
                'Pantry': 'Pantry',
                'Pasta, Rice & Grains': 'Pantry',
                'Period & Incontinence Care': 'Health and Beauty',
                'Personal Care & Hygiene': 'Health and Beauty',
                'Pest Control': 'Garden',
                'Pets': 'Pet',
                'Pork': 'Meat',
                'Poultry': 'Meat',
                'Premixed': 'Miscellaneous',
                'Prepared Vegetables': 'Veg',
                'Ready To Eat Meals': 'Deli',
                'Red Wine': 'Alcoholic Drinks',
                'Rose': 'Alcoholic Drinks',
                'Salads': 'Veg',
                'Sauces': 'Sauces',
                'Sausage': 'Meat',
                'Seafood': 'Seafood',
                'Shopping Bags & Token': None,
                'Shower & Bath Care': 'Health and Beauty',
                'Sliced Breads': 'Bakery',
                'Small Pets': 'Pet',
                'Snacks & Confectionery': 'Snacks',
                'Soft Drinks': 'Non-Alcoholic Drinks',
                'Soups & Noodles': 'Miscellaneous',
                'Sparkling & Champagne': 'Alcoholic Drinks',
                'Speciality Breads & Rolls': 'Bakery',
                'Spirits': 'Alcoholic Drinks',
                'Sports & Energy': 'Non-Alcoholic Drinks',
                'Stocks & Gravy': 'Pantry',
                'Sun & Skin Care': 'Health and Beauty',
                'Tea, Coffee & Hot Chocolate': 'Pantry',
                'Toilet Paper, Tissues & Paper Towels': 'Cleaning',
                'Trees': 'Garden',
                'Vegetarian & Vegan': None,
                'Vitamins, Sports & Nutrition': 'Health Foods',
                'Water': 'Non-Alcoholic Drinks',
                'White Wine': 'Alcoholic Drinks',
                'Yogurt': 'Dairy'},
    'Coles': {   'Air Fresheners & Home Fragrance': 'Home',
                 'Almond & Other Nut Milk': 'Non-Alcoholic Drinks',
                 'Antipasto': None,
                 'Asian Foods': 'International',
                 'Back To School': None,
                 'Bags': 'Miscellaneous',
                 'Barilla': 'Pantry',
                 'Bathroom': 'Cleaning',
                 'Bbq': 'Meat',
                 'Bbq, Sausages & Burgers': 'Meat',
                 'Beef & Veal': 'Meat',
                 'Beer': 'Alcoholic Drinks',
                 'Best Of Spring': None,
                 'Beverages': None,
                 'Birds': 'Pet',
                 'Biscuits & Cookies': 'Snacks',
                 'Bonus Credit Products': None,
                 'Breakfast On The Go': 'Miscellaneous',
                 'Butter & Margarine': 'Dairy',
                 'Canned Food': 'Pantry',
                 'Cask & Fortified Wine': 'Alcoholic Drinks',
                 'Cat & Kitten': 'Pet',
                 'Champagne & Sparkling': 'Alcoholic Drinks',
                 'Cheese': 'Dairy',
                 'Cheese & Biscuits': 'Miscellaneous',
                 'Cheese & Desserts': 'Miscellaneous',
                 'Cheese, Yoghurt & Dairy': 'Dairy',
                 'Chilled Juice': 'Non-Alcoholic Drinks',
                 'Chilled Quiches & Pies': 'Bakery',
                 'Chips, Chocolates & Snacks': 'Snacks',
                 'Chocolates': 'Sweets',
                 'Christmas': None,
                 'Christmas Chocolate': 'Sweets',
                 'Christmas Chocolates': 'Sweets',
                 'Christmas Decorations': None,
                 'Christmas Desserts': 'Sweets',
                 'Christmas Desserts & Chocolate': 'Sweets',
                 'Christmas Drinks & Liquor': 'Alcoholic Drinks',
                 'Christmas Entertaining': None,
                 'Christmas Exclusives': 'Miscellaneous',
                 'Christmas Food Favourites': None,
                 'Christmas Gifting': None,
                 'Christmas Hams': 'Meat',
                 'Christmas Lunch': None,
                 'Christmas Meals': None,
                 'Christmas Sweet Treats & Desserts': 'Sweets',
                 'Cider': 'Alcoholic Drinks',
                 'Cleaning Goods': 'Cleaning',
                 'Clothing & Accessories': 'Clothing',
                 'Coffee & Tea': 'Pantry',
                 'Coles Christmas Exclusives': None,
                 'Coles Finest': None,
                 'Coles Made Easy Range': None,
                 'Condiments & Sauces': 'Miscellaneous',
                 'Crackers & Rice Cakes': 'Snacks',
                 'Crackers, Dips & Pate': 'Miscellaneous',
                 'Craft, Toys & Games': 'Miscellaneous',
                 'Cream & Custard': 'Dairy',
                 'Creams, Custards & Ice Creams': 'Dairy',
                 'Cupboard Essentials': 'Pantry',
                 'Dairy & Lactose Free': 'Dairy',
                 'Dairy Desserts': 'Dairy',
                 'Dairy World Foods': 'Dairy',
                 'Dairy, Chilled & Frozen': None,
                 'Dairy, Eggs & Fridge': None,
                 'Decorations & Tableware': None,
                 'Deli': None,
                 'Deli Meats': 'Meat',
                 'Deli Packaged Meat': 'Meat',
                 'Deli Platter': 'Deli',
                 'Deli Poultry': 'Meat',
                 'Deli Seafood': 'Seafood',
                 'Deliver More Range': None,
                 'Dietary & World Foods': 'Miscellaneous',
                 'Dips': 'Deli',
                 'Dips & Pate': 'Deli',
                 'Dishwashing': 'Cleaning',
                 'Diy & Car': 'Garden',
                 'Dog & Puppy': 'Pet',
                 'Down Down': 'Deals',
                 'Drinks': 'Non-Alcoholic Drinks',
                 'Easy Breakfast': 'Miscellaneous',
                 'Easy Meals': 'Deli',
                 'Easy School Night Dinners': None,
                 'Egg Free': None,
                 'Eggs': 'Eggs',
                 'Electrical': 'Garden',
                 'Entertaining': None,
                 'Exclusive To Coles': None,
                 'Fat Free': None,
                 'Fish &  Seafood': 'Seafood',
                 'Fish Food & Accessories': 'Pet',
                 'Fodmap Friendly': None,
                 'Food Storage': 'Home',
                 'Free From': None,
                 'Fresh Pasta & Noodles': 'Miscellaneous',
                 'Fresh Pasta & Sauces': None,
                 'Frozen': 'Freezer',
                 'Fruit': 'Fruit',
                 'Fruit & Vegetables': None,
                 'Game': 'Meat',
                 'Garden': 'Garden',
                 'Garlic Bread & Pastry Sheets': 'Bakery',
                 'Gluten Free': None,
                 'Gourmet Cheese': 'Dairy',
                 'Grab & Go Snacks': 'Miscellaneous',
                 'Grant Burge': 'Alcoholic Drinks',
                 'Grill': 'Meat',
                 'Gum, Mints & Lozenges': 'Sweets',
                 'Hair & Skin Care': 'Health and Beauty',
                 'Halal': None,
                 'Halal Bbq': 'Meat',
                 'Halal Beef': 'Meat',
                 'Halal Chicken': 'Meat',
                 'Halal Lamb': 'Meat',
                 'Ham': 'Meat',
                 'Health Foods & Diet': 'Health Foods',
                 'Health, Sports & Dietary Foods': 'Health Foods',
                 'Heinz': 'Pantry',
                 'Herbs, Spices & Sauces': 'Miscellaneous',
                 'Home & Garden': 'Miscellaneous',
                 'Home and Garden': 'Miscellaneous',
                 'Homewares': 'Home',
                 'Hot Food': 'Miscellaneous',
                 'Hot Snacks & Sides': 'Miscellaneous',
                 'Household': 'Home',
                 'Indian Food & Meals': 'International',
                 'Indian Foods': 'International',
                 'Italian Meals & Pasta': 'International',
                 'Jacobs Creek': 'Alcoholic Drinks',
                 'Kitchen': 'Home',
                 'Kits & Meal Bases': 'Miscellaneous',
                 'Kosher Beef & Veal': 'Meat',
                 'Kosher Chicken': 'Meat',
                 'Kosher Food': 'International',
                 'Kosher Meat & Seafood': None,
                 'Lamb': 'Meat',
                 'Laundry': 'Cleaning',
                 'Liquor Gifts': 'Miscellaneous',
                 'Liquorland': 'Alcoholic Drinks',
                 'Lollies & Licorice': 'Sweets',
                 'Long Life-Milk': 'Dairy',
                 'Long-Life Flavoured Milk': 'Dairy',
                 'Long-Life-Milk': 'Dairy',
                 'Low Carb & Low Sugar': None,
                 'Low-Mid Strength': 'Alcoholic Drinks',
                 'Lunchbox Snacks': 'Snacks',
                 'Meals & Entertaining': 'Miscellaneous',
                 'Meat & Seafood': None,
                 'Meat Packaged': 'Meat',
                 'Meat, Fish & Poultry': 'Miscellaneous',
                 'Meat, Seafood & Deli': None,
                 'Medicinal Care': 'Health and Beauty',
                 'Milk': 'Dairy',
                 'Mince': 'Meat',
                 'Nescafe': 'Pantry',
                 'New Dairy': 'Dairy',
                 'Non Alcoholic': 'Non-Alcoholic Drinks',
                 'Non-Alcoholic Drinks': 'Non-Alcoholic Drinks',
                 'Nut Free': 'Pantry',
                 'Nuts & Dried Fruit': 'Fruit',
                 'Oat Milk': 'Pantry',
                 'Olives': None,
                 'Organic Fruits': 'Fruit',
                 'Organic Fruits & Vegetables': None,
                 'Organic Meat': 'Meat',
                 'Other': 'Miscellaneous',
                 'Other Halal': 'Miscellaneous',
                 'Other Ready Meals': 'Deli',
                 'Outdoors': 'Garden',
                 'Packaged Deli Meats': 'Meat',
                 'Packaged Ham': 'Meat',
                 'Packaged Salad': 'Veg',
                 'Pantry': 'Pantry',
                 'Pantry Items': 'Pantry',
                 'Party Supplies': 'Home',
                 'Passover': 'Miscellaneous',
                 'Pasta Sauces': 'Pantry',
                 'Pastry': 'Freezer',
                 'Peanut Free': None,
                 'Personal & Baby Care': None,
                 'Pest Control': 'Garden',
                 'Pet': 'Pet',
                 'Pies & Pastries': 'Bakery',
                 'Pizza, Pasta & Sauces': 'Miscellaneous',
                 'Pizzas': 'Freezer',
                 'Platters & Antipasto': 'Miscellaneous',
                 'Pork': 'Meat',
                 'Poultry': 'Meat',
                 'Powdered Long Life Milk': 'Dairy',
                 'Pre-Made Platters': None,
                 'Pre-Marinated Meats & Ready Meals': 'Deli',
                 'Premixed Drinks': 'International',
                 'Prepacked Olives & Antipasto': 'Deli',
                 'Prepared Vegetable': 'Veg',
                 'Ready To Eat': None,
                 'Ready To Eat Meals': None,
                 'Red Wine': 'Alcoholic Drinks',
                 'Reusable Shopping Bags': 'Home',
                 'Rose': 'Alcoholic Drinks',
                 'Salad & Herbs': 'Veg',
                 'Sandwich & Wrap Essentials': None,
                 'Sandwiches': 'Deli',
                 'School Accessories & Lunchboxes': 'Home',
                 'School Breakfast': None,
                 'School Lunches': None,
                 'Scoop & Weigh': 'Health Foods',
                 'Seafood': 'Seafood',
                 'Serving & Tableware': 'Miscellaneous',
                 'Slow Cook': None,
                 'Small Pets': 'Pet',
                 'Snacks': 'Snacks',
                 'Snacks & Confectionery': 'Miscellaneous',
                 'Soft Drink & Energy Drinks': 'Non-Alcoholic Drinks',
                 'Soft Drinks & Mixers': 'Miscellaneous',
                 'Softdrink Mixers': 'Non-Alcoholic Drinks',
                 'Soups & Stews': 'Deli',
                 'South African': 'Miscellaneous',
                 'Soy Free': None,
                 'Soy Milk': 'Non-Alcoholic Drinks',
                 'Specialty Brands': None,
                 'Spirits': 'Alcoholic Drinks',
                 'Sporting Essentials': 'Home',
                 'Sports Nutrition': 'Health Foods',
                 'Spreads & Dips': 'Deli',
                 'Stationery & Media': 'Home',
                 'Sugar Free': None,
                 'Sweets & Snacks': 'Miscellaneous',
                 'Thai Meals': 'International',
                 'Toilet Paper, Tissues & Paper Towels': 'Cleaning',
                 'Vegan & Vegetarian': None,
                 'Vegetables': 'Veg',
                 'Vegetarian & Vegan': None,
                 'Water & Juices': 'Non-Alcoholic Drinks',
                 'White Wine': 'Alcoholic Drinks',
                 'Yoghurt': 'Dairy'},
    'Iga': {   'Baby': 'Baby',
               'Bakery': 'Bakery',
               'Cheese': 'Dairy',
               'Chilled And Fresh': None,
               'Chilled Bread': 'Freezer',
               'Coffee': 'Pantry',
               'Cordials, Juices And Iced Teas': 'Non-Alcoholic Drinks',
               'Cream, Custards And Desserts': 'Miscellaneous',
               'Dairy, Eggs And Fridge': None,
               'Deli': 'Deli',
               'Deli Specialties': 'Deli',
               'Drinks': None,
               'Eggs': 'Eggs',
               'Eggs, Butter And Margarine': None,
               'Essentials': 'Miscellaneous',
               'Flavoured Milk Drinks': 'Dairy',
               'Fresh Pasta And Pasta Sauces': 'Deli',
               'Front Of House': None,
               'Frozen': 'Freezer',
               'Fruit And Vegetable': 'Fruit',
               'Grocery': None,
               'Health And Beauty': 'Health and Beauty',
               'Home and Garden': 'Miscellaneous',
               'Hot Drinks': 'Non-Alcoholic Drinks',
               'Household': 'Home',
               'Lifestyle Beverages': 'Non-Alcoholic Drinks',
               'Liquor': 'Alcoholic Drinks',
               'Long Life Milk': 'Dairy',
               'Meat': 'Meat',
               'Meat, Seafood And Deli': None,
               'Milk And Cream': 'Dairy',
               'Non-Alcoholic': 'Non-Alcoholic Drinks',
               'Other': None,
               'Pantry': 'Pantry',
               'Pet': 'Pet',
               'Ready To Eat Meals': 'Deli',
               'Seafood': 'Seafood',
               'Smallgoods': None,
               'Soft Drinks': 'Non-Alcoholic Drinks',
               'Sports And Energy Drinks': 'Non-Alcoholic Drinks',
               'Spreads': 'Miscellaneous',
               'Tea': 'Pantry',
               'Tobacco': None,
               'Vegetarian And Vegan': None,
               'Water': 'Non-Alcoholic Drinks',
               'Yoghurt': 'Dairy'},
    'Woolworths': {   'Air Fry Guy': None,
                      'Air Fryer Ready': None,
                      'Air Fryer Ready Meals': None,
                      'Air Fryers & Cookers': 'Home',
                      'Almond & Other Nut Milks': 'Non-Alcoholic Drinks',
                      'Almond Milk': 'Non-Alcoholic Drinks',
                      'American & Canadian Whiskey': 'Alcoholic Drinks',
                      'Antipasto': 'Non-Alcoholic Drinks',
                      'Apples & Pears': 'Fruit',
                      'Arts & Craft': None,
                      'Asian': 'International',
                      'Asian & Exotic Fruit': 'Fruit',
                      'Asian Ready Meals': 'Non-Alcoholic Drinks',
                      'Assorted Desserts': 'Sweets',
                      'Assorted Frozen Desserts': 'Freezer',
                      'Australian Beer': 'Alcoholic Drinks',
                      'Avocados': 'Fruit',
                      'Baby': 'Baby',
                      'Baby & Toddler Clothing': 'Baby',
                      'Baby Food': 'Baby',
                      'Baby Food 4 Months+': 'Baby',
                      'Baby Formula & Toddler Milk': 'Baby',
                      'Baby Furniture': 'Baby',
                      'Bake At Home': None,
                      'Bakery': 'Bakery',
                      'Bakery & Desserts': None,
                      'Bakery Cakes': 'Bakery',
                      'Bakery Snacks': 'Bakery',
                      'Baking': 'International',
                      'Bananas': 'Fruit',
                      'Barbecues & Accessories': None,
                      'Bars': 'Pantry',
                      'Bath & Skincare': 'Health and Beauty',
                      'Batteries & Power': 'Home',
                      'Bbq Meat': 'Meat',
                      'Bbq Ready': None,
                      'Beauty': 'Health and Beauty',
                      'Beauty Tools & Nails': 'Health and Beauty',
                      'Beef & Pork': 'Meat',
                      'Beef & Veal': 'Meat',
                      'Beer': 'Alcoholic Drinks',
                      'Beer & Cider': 'Alcoholic Drinks',
                      'Beer, Wine & Spirits': 'Alcoholic Drinks',
                      'Berries & Cherries': 'Fruit',
                      'Berries & Tropical': 'Fruit',
                      'Birds, Fish & Small Pets': 'Pet',
                      'Biscuit Multipacks': 'Snacks',
                      'Biscuits & Crackers': 'Snacks',
                      'Blenders & Food Processors': 'Home',
                      'Board Games & Puzzles': 'Non-Alcoholic Drinks',
                      'Bon Bons & Partyware': 'Home',
                      'Bones, Joints & Muscle Health': 'Health and Beauty',
                      'Boys & Girls Socks': 'Clothing',
                      'Boys & Girls Underwear': 'Clothing',
                      'Brain & Heart': 'Health and Beauty',
                      'Bread Mix': 'Bakery',
                      'Bread Rolls': 'Bakery',
                      'Breakfast': None,
                      'Breakfast & Spreads': None,
                      'Breakfast Cereal': 'Pantry',
                      'Broccoli, Cauliflower & Cabbage': 'Veg',
                      'Burgers, Rissoles & Meatballs': 'Meat',
                      'Butter & Margarine': 'Dairy',
                      'Bws': 'Alcoholic Drinks',
                      'Cabernet Sauvignon': 'Alcoholic Drinks',
                      'Cadbury': 'Sweets',
                      'Cake & Dessert Mix': 'Sweets',
                      'Cakes': 'Bakery',
                      'Cakes & Biscuits': 'Sweets',
                      'Cakes & Cheesecakes': 'Bakery',
                      'Canned Food & Instant Meals': 'Pantry',
                      'Canned Salmon & Seafood': 'Seafood',
                      'Canned Soup & Soup Ingredients': 'Pantry',
                      'Canned Tuna': 'Seafood',
                      'Cask Wine': 'Alcoholic Drinks',
                      'Cat & Kitten': 'Pet',
                      "Cc'S": 'Snacks',
                      'Champagne & Sparkling': 'Alcoholic Drinks',
                      'Chardonnay': 'Alcoholic Drinks',
                      'Cheese': 'Dairy',
                      'Cheese Slices & Blocks': 'Dairy',
                      'Cheese, Crackers & Dips': None,
                      'Chicken': 'Meat',
                      "Children'S Health": 'Health and Beauty',
                      'Chilled Asian': 'Freezer',
                      'Chilled Water': 'Non-Alcoholic Drinks',
                      'Chips': 'Snacks',
                      'Chips Multi-Pack': 'Snacks',
                      'Chips Sharing': 'Snacks',
                      'Chips Single Pack': 'Snacks',
                      'Chocolate Bars': 'Sweets',
                      'Chocolate Bites': 'Sweets',
                      'Chocolate Blocks': 'Sweets',
                      'Chocolate Sharing': 'Sweets',
                      'Chocolates & Lollies': 'Sweets',
                      'Chopping Boards': 'Home',
                      'Christmas': None,
                      'Christmas Biscuits & Wafers': 'Sweets',
                      'Christmas Cards, Wrapping & Bags': None,
                      'Christmas Hams': 'Meat',
                      'Christmas Pork, Lamb & Turkey': 'Meat',
                      'Christmas Trees': None,
                      'Chutney & Relish': 'Sauces',
                      'Cider': 'Alcoholic Drinks',
                      'Citrus Fruit': 'Fruit',
                      'Classics & More Cuisines': 'International',
                      'Cleaning & Maintenance': 'Cleaning',
                      'Cleansers & Toners': 'Health and Beauty',
                      'Clothing & Accessories': 'Clothing',
                      'Coca-Cola Zero Sugar': 'Non-Alcoholic Drinks',
                      'Coffee Machines & Milk Frothers': 'Home',
                      'Cold, Flu & Allergies': 'Health and Beauty',
                      'Coleslaw': None,
                      'Condiments': 'Sauces',
                      'Confectionery': 'Sweets',
                      'Connoisseur': 'Freezer',
                      'Cook Range': None,
                      'Cooking Cheese': 'Dairy',
                      'Cordials, Juices & Iced Teas': 'Non-Alcoholic Drinks',
                      'Corn Chips & Salsa': None,
                      'Cosmetics': 'Health and Beauty',
                      'Costumes & Accessories': 'Clothing',
                      'Crackers': 'Snacks',
                      'Craft Beer': 'Alcoholic Drinks',
                      'Crawling Insects': 'Garden',
                      'Cream': 'Dairy',
                      'Cream, Custard & Desserts': None,
                      'Crumbed': None,
                      'Crumbed Chicken & Fish': None,
                      'Crumpets & Pancakes': None,
                      'Cucumber': 'Veg',
                      'Custards, Creams & Egg Nog': 'Dairy',
                      'Cut Veg': 'Veg',
                      'Dairy, Eggs & Fridge': None,
                      'Darrell Lea': 'Sweets',
                      'Decorations': None,
                      'Decorations & Activities': None,
                      'Decorations & Festive Dried Fruits': None,
                      'Deli': 'Deli',
                      'Deli Chicken': 'Meat',
                      'Deli Meats': 'Meat',
                      'Deli Specialties': None,
                      'Denture Care': 'Health and Beauty',
                      'Desserts': None,
                      'Dietary Needs': None,
                      'Digestion & Probiotics': 'Health and Beauty',
                      'Digestive Health': 'Health and Beauty',
                      'Dining & Entertaining': None,
                      'Dinner': None,
                      'Dips': 'Deli',
                      'Dips & Pate': 'Deli',
                      'Dolls & Action Figures': 'Miscellaneous',
                      'Doritos': 'Snacks',
                      'Dried Fruit': 'Pantry',
                      'Dried Herbs & Spices': 'Spices',
                      'Dried Pasta': 'Pantry',
                      'Drinks': None,
                      'Drinks & Powders': 'Non-Alcoholic Drinks',
                      'Dumplings': None,
                      'Education & Learning': None,
                      'Educational & Early Learning': None,
                      'Eerie Entertaining': None,
                      'Eggs': 'Eggs',
                      'Eggs, Butter & Margarine': None,
                      'Electronics': 'Electronics',
                      'Entertaining': None,
                      'Entertaining Sides': None,
                      'European': 'International',
                      'European Foods': 'International',
                      'European, Uk & Irish': None,
                      'Everyday Yoghurt': 'Dairy',
                      'Face Masks & Patches': 'Health and Beauty',
                      'Face Moisturisers': 'Health and Beauty',
                      'Fanta': 'Non-Alcoholic Drinks',
                      'Fatigue, Stress & Sleep': 'Health and Beauty',
                      'Festive Chocolates & Treats': 'Sweets',
                      'Festive Hats & Accessories': None,
                      "Fetta & Goat'S Cheese": 'Dairy',
                      'Fish Fillets': 'Seafood',
                      'Flavoured Milk': 'Dairy',
                      'Flavoured Milk & Drinks': None,
                      'Flavouring, Essence & Food Colouring': None,
                      'Flour': 'Pantry',
                      'Food Gifting': None,
                      'Footwear & Shoe Care': 'Clothing',
                      'Fortified & Cask Wine': 'Alcoholic Drinks',
                      'Fragrance': 'Health and Beauty',
                      'Free Range Chicken': 'Meat',
                      'Freezer': 'Freezer',
                      'Fresh Chicken': 'Meat',
                      'Fresh Herbs, Garlic & Chillies': 'Spices',
                      'Fresh Pasta & Noodles': 'Deli',
                      'Fresh Pasta & Sauces': None,
                      'Frozen Desserts': 'Freezer',
                      'Frozen Dumplings': 'Freezer',
                      'Frozen Fruit': 'Freezer',
                      'Frozen Gluten Free': 'Freezer',
                      'Frozen Meals': 'Freezer',
                      'Frozen Pies & Sausage Rolls': 'Freezer',
                      'Frozen Seafood': 'Seafood',
                      'Frozen Vegetables': 'Freezer',
                      'Frozen Yoghurt': 'Freezer',
                      'Fruit': 'Fruit',
                      'Fruit & Veg': None,
                      'Full Cream Milk': 'Dairy',
                      'Full Strength Beer': 'Alcoholic Drinks',
                      'Garden Decorations': 'Garden',
                      'Garlic, Chillies & Spices': 'Spices',
                      'Gelato & Sorbet': 'Freezer',
                      'Gifts': None,
                      'Gifts For Kids': None,
                      'Gifts, Wrapping & Cards': None,
                      'Ginger Beer': 'Alcoholic Drinks',
                      'Gluten Free': None,
                      'Gluten Free Bakery': 'Bakery',
                      'Gluten Free Pasta': 'Pantry',
                      'Gluten Free Snacks': 'Snacks',
                      'Grapes': 'Fruit',
                      'Grated Cheese': 'Dairy',
                      'Greek Yoghurt & Natural Yoghurt': 'Dairy',
                      'Gum, Mints & Lozenges': 'Sweets',
                      'Hair Accessories & Brushes': 'Health and Beauty',
                      'Hair Care': 'Health and Beauty',
                      'Hair, Skin & Nails': 'Health and Beauty',
                      'Halloween': None,
                      'Health': 'Health and Beauty',
                      'Health & Safety': None,
                      'Health & Wellness': 'Health and Beauty',
                      'Health Foods': 'Health Foods',
                      'Health Meal Options': 'Health Foods',
                      'Healthier Lunch Box': None,
                      'Heinz': None,
                      'High Protein': 'Health Foods',
                      'High Protein Yoghurt': 'Dairy',
                      'Home & Lifestyle': None,
                      'Home Brew': None,
                      'Home Decorations': None,
                      'Honey': 'Pantry',
                      'Hosiery': 'Clothing',
                      'Ice Cream': 'Freezer',
                      'Ice Cream & Toppings': 'Freezer',
                      'Ice Cream Cakes': 'Freezer',
                      'Ice Cream Cones, Syrups & Toppings': 'Pantry',
                      'Ice Cream Tubs': 'Freezer',
                      'Icing & Cake Decorating': 'Pantry',
                      'In-Store Bakery': 'Bakery',
                      'Indian': 'International',
                      'Indian & South Asian': None,
                      'Indoor Lights': None,
                      'Interactive Toys': 'Miscellaneous',
                      'International Beer': 'Alcoholic Drinks',
                      'International Foods': 'International',
                      'International Meals': 'International',
                      'Intimate Wellness': 'Health and Beauty',
                      'Italian': 'International',
                      'Italian Ready Meals': None,
                      "Jack Link'S": 'Snacks',
                      'Jam': 'Pantry',
                      'Jatz': 'Snacks',
                      'Jelly': 'Sweets',
                      'Kebabs & Marinated': 'Meat',
                      'Kefir': 'Dairy',
                      'Kettle': None,
                      'Kettles & Water Purifiers': 'Home',
                      "Kid'S Frozen Meals": 'Freezer',
                      'Kids Drinks': 'Non-Alcoholic Drinks',
                      'Kids Snacks & Lunch': None,
                      'Kids Yoghurt': 'Dairy',
                      'Kinder': 'Sweets',
                      'Kitchen': None,
                      'Kitchen Appliances': 'Home',
                      'Kitchen Organisation': 'Home',
                      'Kitchenware & Storage': None,
                      'Knives': 'Home',
                      'Lactose Free': 'Dairy',
                      'Lactose Free Milk': 'Dairy',
                      'Lamb': 'Meat',
                      'Lamb Mince': 'Meat',
                      'Lettuce, Kale & Leafy Greens': 'Veg',
                      'Life Savers': 'Sweets',
                      'Light & Low Carb Beer': 'Alcoholic Drinks',
                      'Lights & Animated Decor': 'Home',
                      'Lindt': 'Sweets',
                      'Liqueurs': 'Alcoholic Drinks',
                      'Lozenges': 'Health and Beauty',
                      'Lunch Box': None,
                      'Lunch Box Snacks': None,
                      'Lunch Boxes & Drink Bottles': None,
                      'Lunch, Dinner & Entertaining': None,
                      "M&M'S": 'Sweets',
                      'Marinades & Seasoning': None,
                      'Mars': 'Sweets',
                      'Meal Kits': None,
                      'Meal Kits & Ingredients': None,
                      'Meal Occasions': None,
                      'Meat': 'Meat',
                      'Meat, Poultry & Ham': 'Meat',
                      'Melons & Mangoes': 'Fruit',
                      "Men'S Body Sprays": 'Health and Beauty',
                      "Men'S Care": 'Health and Beauty',
                      "Men'S Clothing & Underwear": 'Clothing',
                      "Men'S Hair Care": 'Health and Beauty',
                      "Men'S Health": 'Health and Beauty',
                      "Men'S Skin": 'Health and Beauty',
                      "Men'S Socks": 'Clothing',
                      'Merlot': 'Alcoholic Drinks',
                      'Mexican': 'International',
                      'Microwave Ready': None,
                      'Middle Eastern': 'International',
                      'Milk': 'Dairy',
                      'Milky Way': 'Sweets',
                      'Mince': 'Meat',
                      'Mixers': 'Non-Alcoholic Drinks',
                      'Model Building & Construction': 'Miscellaneous',
                      'Moscato & Sweet Whites': 'Alcoholic Drinks',
                      'Mount Franklin Lightly Sparkling': 'Non-Alcoholic '
                                                          'Drinks',
                      'Muesli & Oats': 'Pantry',
                      'Muesli Bars & Snack Bars': 'Snacks',
                      'Muffins & Pastries': 'Bakery',
                      'Muffins & Scones': 'Bakery',
                      'Multi Vitamins': 'Health and Beauty',
                      'Muscat & Other Varieties': 'Miscellaneous',
                      'Mustard': 'Sauces',
                      'Nappies': 'Health and Beauty',
                      'Nappies 18 Months+ (10Kg+)': 'Baby',
                      'Nappies 3-6 Months (5-7Kg)': 'Baby',
                      'Newborn Nappies (3-5Kg)': 'Baby',
                      'Non-Fiction': 'Miscellaneous',
                      'Oat & Rice Milk': 'Non-Alcoholic Drinks',
                      'Oil & Vinegar': 'Pantry',
                      'Omega-3': 'Health and Beauty',
                      'Oral Care': 'Health and Beauty',
                      'Organic': None,
                      'Organic Bakery': 'Bakery',
                      'Organic Beef': 'Meat',
                      'Organic Fruit': 'Fruit',
                      'Organic Loose': 'Veg',
                      'Organic Meat': 'Meat',
                      'Organic Meat & Poultry': 'Meat',
                      'Organic Salad': None,
                      'Organic Vegetables': 'Veg',
                      'Other Red Varietals': 'Alcoholic Drinks',
                      'Outdoor Lights': None,
                      'Outdoor Living': None,
                      'Oven Ready Meals': 'Deli',
                      'Oven Ready Meat': 'Meat',
                      'Oysters, Mussels & Scallops': 'Seafood',
                      'Packaged Bread & Bakery': 'Bakery',
                      'Pamper & Beauty Gifts': 'Health and Beauty',
                      'Pancake Mix': 'Pantry',
                      'Pancakes': 'International',
                      'Pantry': 'Pantry',
                      'Parmesan & Italian Cheese': 'Dairy',
                      'Party Supplies': None,
                      'Party Tableware': None,
                      'Pasta & Sauces': 'International',
                      'Pasta Meals': 'Deli',
                      'Pasta Sheets': 'Pantry',
                      'Pasta, Rice & Grains': 'Pantry',
                      'Pastries & Desserts': 'Bakery',
                      'Peanut Butter': 'Pantry',
                      'Peas, Beans, Corn & Asparagus': 'Veg',
                      'Pepsi': 'Non-Alcoholic Drinks',
                      'Period & Continence Care': 'Health and Beauty',
                      'Personal Care': 'Health and Beauty',
                      'Pest Control': 'Garden',
                      'Pet': 'Pet',
                      'Peters': 'Freezer',
                      'Pickled Vegetables': 'Pantry',
                      'Pies, Pastries & Quiches': 'Snacks',
                      'Pink Moscato & Sweet Reds': 'Alcoholic Drinks',
                      'Pinot Noir': 'Alcoholic Drinks',
                      'Pizza Bases': 'Freezer',
                      'Plant Based': None,
                      'Plant Based Meals': None,
                      'Plant Based Yoghurt': 'Dairy',
                      'Platters': 'Miscellaneous',
                      'Platters & Grazing Board Essentials': 'Deli',
                      'Popcorn': 'Pantry',
                      'Pork & Lamb': 'Meat',
                      'Pork Mince': 'Meat',
                      'Port': 'Alcoholic Drinks',
                      'Potatoes & Pumpkins': 'Veg',
                      'Poultry': 'Meat',
                      'Poultry, Meat & Seafood': None,
                      'Pre-Made Tarts & Pies': 'Deli',
                      'Pre-Prepared': 'Deli',
                      'Pregnancy & Family Planning': 'Health and Beauty',
                      'Pregnancy Care & Family Planning': 'Health and Beauty',
                      'Pregnancy Tests': 'Health and Beauty',
                      'Premium Ice Cream': 'Freezer',
                      'Premixed Drinks': 'Non-Alcoholic Drinks',
                      'Prepacked Vegetables': 'Veg',
                      'Prepared Salads & Bowls': 'Veg',
                      'Pretzels & Jerky': 'Snacks',
                      'Pringles': 'Snacks',
                      'Quinoa, Cous Cous & Other Grains': 'Pantry',
                      'Ready Made Cookies & Donuts': 'Snacks',
                      'Ready Made Desserts': 'Sweets',
                      'Ready Meals': None,
                      'Ready To Cook': 'Deli',
                      'Ready To Eat': 'Deli',
                      'Ready To Freeze Ice Blocks': None,
                      'Ready To Go Meals': 'Deli',
                      'Red Blends': 'Alcoholic Drinks',
                      'Red Wine': 'Alcoholic Drinks',
                      'Red Wine Cans': 'Alcoholic Drinks',
                      "Reese'S": 'Snacks',
                      'Rice': 'Pantry',
                      'Rice & Bread': None,
                      'Rice & Noodles': 'Pantry',
                      'Ricotta, Cottage & Cream Cheese': None,
                      'Rodents': 'Garden',
                      'Rolls & Bagels': 'Bakery',
                      'Sakata': 'Snacks',
                      'Salad': None,
                      'Salad Bags': None,
                      'Salad Bowls': 'Deli',
                      'Salad Kits': 'Veg',
                      'Sandwich Ingredients': None,
                      'Sauces': 'Sauces',
                      'Sauces & Condiments': 'Sauces',
                      'Sauces & Salsa': 'Sauces',
                      'Sauces & Seasonings': 'Miscellaneous',
                      'Sausages & Frankfurts': 'Meat',
                      'Savoury Snacks': 'Snacks',
                      'Savoury Spread': 'Pantry',
                      'Seafood': 'Seafood',
                      'Secret Santa Gifts': None,
                      'Security & Smart Home': 'Home',
                      'Self Tanning': 'Health and Beauty',
                      'Serums': 'Health and Beauty',
                      'Shapes': 'Snacks',
                      'Sherry': 'Alcoholic Drinks',
                      'Shiraz': 'Alcoholic Drinks',
                      'Shiraz Blends': 'Alcoholic Drinks',
                      'Single Meals': 'Deli',
                      'Skim & Reduced Fat Milk': 'Dairy',
                      'Skincare': 'Health and Beauty',
                      'Skincare & Body': 'Health and Beauty',
                      'Skittles': 'Snacks',
                      'Sliced Cheese': 'Dairy',
                      "Smith'S": 'Snacks',
                      'Snacking': 'Snacks',
                      'Snacking Cheese': None,
                      'Snacking Fruit': None,
                      'Snacks': 'Snacks',
                      'Snacks & Confectionery': 'Baby',
                      'Soft Cheese': 'Dairy',
                      'Soft Drink Bottles': 'Alcoholic Drinks',
                      'Soft Drinks': 'Non-Alcoholic Drinks',
                      'Soft Plush Toys': None,
                      'Soups': None,
                      'Sourdough & Specialty Bread': 'Bakery',
                      'Soy & Asian Sauces': 'International',
                      'Soy Milk': 'Non-Alcoholic Drinks',
                      'Sparkling Ros�': 'Alcoholic Drinks',
                      'Sparkling Sweet Wine': 'Alcoholic Drinks',
                      'Sparkling Water': 'Non-Alcoholic Drinks',
                      'Spice & Seasonings': 'Spices',
                      'Spinach & Rocket': 'Veg',
                      'Spirits': 'Alcoholic Drinks',
                      'Sport & Outdoor Toys': 'Garden',
                      'Sports Nutrition Powders': 'Health and Beauty',
                      'Spreads': None,
                      'Spring Gardening - While Stocks Last': 'Garden',
                      'Sprite': 'Non-Alcoholic Drinks',
                      'Squid, Octopus & Marinara': 'Seafood',
                      'Stationery': 'Home',
                      'Stationery & Office Supplies': None,
                      'Still Water': 'Non-Alcoholic Drinks',
                      'Stir Fry & Soup Kits': None,
                      'Stone Fruit': 'Fruit',
                      'Stove Top Meals': 'Deli',
                      'Summer': None,
                      'Sun Protection': 'Health and Beauty',
                      'Sweet Chilli & Hot Sauce': 'Sauces',
                      'Sweet Spread': 'Pantry',
                      'Sweets & Treats': 'Sweets',
                      'Sweets, Treats And Desserts': 'Sweets',
                      'Table & Hanging Decorations': None,
                      'Table & Kitchenware': None,
                      'Tableware & Partyware': None,
                      'Tea': 'Pantry',
                      'Tea & Coffee': 'Pantry',
                      'Teeth Whitening': 'Health and Beauty',
                      'Tequila': 'Alcoholic Drinks',
                      'The Natural Confectionery Co.': 'Sweets',
                      'Thick & Creamy Yoghurt': 'Dairy',
                      'Toilet Paper, Tissues & Paper Towels': 'Cleaning',
                      'Tomato & Bbq Sauce': 'Sauces',
                      'Tortillas, Tacos & Chips': 'Pantry',
                      'Toy Cars & Trucks': None,
                      'Toys': None,
                      'Toys & Games': None,
                      'Toys & Playtime': None,
                      'Trays & Bakes': None,
                      'Tree Decorations': None,
                      'Trees & Decorations': None,
                      'Twisties': 'Snacks',
                      'Uk & Irish Foods': 'International',
                      'Uk Foods': 'International',
                      'Umbrellas': 'Garden',
                      'Vegan': None,
                      'Vegan & Vegetarian': None,
                      'Vegetables': 'Veg',
                      'Vegetarian & Meat Free': None,
                      'Vegetarian & Vegan': None,
                      'Vinegar': 'Pantry',
                      'Vitamins': 'Health and Beauty',
                      'Vodka': 'Alcoholic Drinks',
                      'Washed & Cut Vegetables': 'Veg',
                      'Water': 'Non-Alcoholic Drinks',
                      'Waxes & Creams': 'Health and Beauty',
                      'Weight Management': 'Health and Beauty',
                      'Wellness Meals': 'Health Foods',
                      'White Blends': 'Miscellaneous',
                      'White Wine': 'Alcoholic Drinks',
                      'White Wine Cans': 'Alcoholic Drinks',
                      'Wipes & Changing': 'Baby',
                      'Wok & Pan': None,
                      "Women'S Blades & Razors": 'Health and Beauty',
                      "Women'S Clothing & Underwear": 'Clothing',
                      "Women'S Hair Removal": 'Health and Beauty',
                      "Women'S Health": 'Health and Beauty',
                      "Women'S Socks": 'Clothing',
                      'Woolworths Festive Range': None,
                      'Wraps & Flatbread': 'Pantry',
                      'Yoghurt': 'Dairy',
                      'Yoghurt Pots & Pouches': 'Dairy',
                      'Zucchini, Eggplant & Squash': 'Veg'}}