CATEGORY_MAPPINGS = {
    "Aldi": {
        "Air Fresheners & Fragrances": "Cleaning",
        "Baby": "Baby",
        "Baby Food": "Baby",
        "Baby Nappies & Wipes": "Baby",
        "Bakery": "Bakery",
        "Baking": "Bakery",
        "Bathroom": "Cleaning",
        "Beef": "Meat",
        "Beer": "Alcoholic Drinks",
        "Birds": "Pet",
        "Butter & Margarine": "Dairy",
        "Cakes, Puddings & Pies": "Snacks",
        "Canned Food": "Pantry",
        "Cat & Kitten": "Pet",
        "Cereals & Muesli": "Pantry",
        "Cheese": "Dairy",
        "Chips & Wedges": "Freezer",
        "Chips, Corn Chips & Other": "Snacks",
        "Antipasto": "Miscellaneous",
        "Baby Formula": "Baby",
        "Advent Calendars": "Miscellaneous",
        "Christmas": "Miscellaneous",
        "Cider": "Alcoholic Drinks",
        "Cleaning": "Cleaning",
        "Cleaning & Home and Garden": "Cleaning",
        "Collectables": "Miscellaneous",
        "Condiments & Dressings": "Pantry",
        "Cosmetics": "Health and Beauty",
        "Creams & Custards": "Dairy",
        "Dairy, Eggs & Fridge": "Miscellaneous",
        "Decorations": "Home and Garden",
        "Deli & Chilled Meats": "Meat",
        "Deli Meats": "Meat",
        "Dental Care": "Health and Beauty",
        "Biscuit & Cookies": "Sweets",
        "Biscuits & Cookies": "Sweets",
        "Chocolate": "Sweets",
        "Confectionery": "Sweets",
        "Crackers & Crisp Breads": "Snacks",
        "Desserts": "Sweets",
        "Dips & Spreads": "Snacks",
        "Dogs & Puppy": "Pet",
        "Dried Fruits, Nuts & Jerky": "Fruit",
        "Drinks": "Alcoholic Drinks",
        "Eggs": "Eggs",
        "First Aid & Medicinal": "Health and Beauty",
        "Fish": "Meat",
        "Flavoured Milk": "Sweets",
        "Freezer": "Freezer",
        "Fresh Fruits": "Fruit",
        "Fresh Herbs": "Home and Garden",
        "Fresh Vegetables": "Veg",
        "Front Of Store": "Miscellaneous",
        "Frozen Desserts": "Freezer",
        "Frozen Fruit & Vegetables": "Fruit",
        "Frozen Meat & Seafood": "Meat",
        "Frozen Party Food": "Freezer",
        "Frozen Party Food & Snacks": "Snacks",
        "Frozen Pizzas": "Freezer",
        "Frozen Ready Meals": "Freezer",
        "Fruits & Vegetables": "Fruit",
        "Gift Wrapping & Gifts": "Miscellaneous",
        "Hair Care": "Health and Beauty",
        "Hair Removal": "Health and Beauty",
        "Health & Beauty": "Health and Beauty",
        "Health Foods": "Health and Beauty",
        "Herbs & Spices": "Spices",
        "Home Essentials": "Home and Garden",
        "Ice Cream Snacks": "Freezer",
        "Ice Cream Tubs": "Freezer",
        "Jams & Spreads": "Pantry",
        "Juices & Cordials": "Pantry",
        "Kids Craft": "Miscellaneous",
        "Kitchen": "Home and Garden",
        "Kitchen & Tableware": "Home and Garden",
        "Lamb": "Meat",
        "Laundry": "Cleaning",
        "Lighting": "Home and Garden",
        "Liquor": "Alcoholic Drinks",
        "Lollies & Sweets": "Sweets",
        "Long Life Milk": "Dairy",
        "Lunch Box": "Miscellaneous",
        "Meal Kits": "Miscellaneous",
        "Meat & Seafood": "Miscellaneous",
        "Milk": "Dairy",
        "Muffins, Cakes & Other": "Sweets",
        "Nibbles": "Snacks",
        "Oils & Vinegars": "Pantry",
        "Pantry": "Pantry",
        "Pasta, Rice & Grains": "Pantry",
        "Period & Incontinence Care": "Health and Beauty",
        "Personal Care & Hygiene": "Health and Beauty",
        "Pest Control": "Home and Garden",
        "Pets": "Pet",
        "Pork": "Meat",
        "Poultry": "Meat",
        "Premixed": "Miscellaneous",
        "Prepared Vegetables": "Veg",
        "Ready To Eat Meals": "Miscellaneous",
        "Red Wine": "Alcoholic Drinks",
        "Rose": "Alcoholic Drinks",
        "Salads": "Veg",
        "Sauces": "Pantry",
        "Sausage": "Meat",
        "Seafood": "Seafood",
        "Shopping Bags & Token": "Miscellaneous",
        "Shower & Bath Care": "Health and Beauty",
        "Sliced Breads": "Bakery",
        "Small Pets": "Pet",
        "Snacks & Confectionery": "Snacks",
        "Soft Drinks": "Non-Alcoholic Drinks",
        "Soups & Noodles": "Miscellaneous",
        "Sparkling & Champagne": "Alcoholic Drinks",
        "Speciality Breads & Rolls": "Bakery",
        "Spirits": "Alcoholic Drinks",
        "Sports & Energy": "Non-Alcoholic Drinks",
        "Stocks & Gravy": "Pantry",
        "Sun & Skin Care": "Health and Beauty",
        "Tea, Coffee & Hot Chocolate": "Pantry",
        "Toilet Paper, Tissues & Paper Towels": "Cleaning",
        "Trees": "Home and Garden",
        "Vegetarian & Vegan": "Veg",
        "Water": "Pantry",
        "White Wine": "Alcoholic Drinks",
        "Yogurt": "Dairy",
        "Limited Time Only": "Deals",
        "Iced Tea & Kombucha": "Health Foods",
        "Vitamins, Sports & Nutrition": "Health Foods",
        "Liquor & Drinks": "Miscellaneous",
        "Flowers": "Miscellaneous"
    },
    "Coles": {
        "Almond & Other Nut Milk": "Pantry",
        "Back To School": "Miscellaneous",
        "Barilla": "Pantry",
        "Bbq, Sausages & Burgers": "Meat",
        "Beef & Veal": "Meat",
        "Best Of Spring": "Miscellaneous",
        "Beverages": "Miscellaneous",
        "Birds": "Pet",
        "Biscuits & Cookies": "Snacks",
        "Bonus Credit Products": "Miscellaneous",
        "Butter & Margarine": "Dairy",
        "Cask & Fortified Wine": "Alcoholic Drinks",
        "Cat & Kitten": "Pet",
        "Champagne & Sparkling": "Alcoholic Drinks",
        "Cheese": "Dairy",
        "Chips, Chocolates & Snacks": "Snacks",
        "Chocolates": "Sweets",
        "Cider": "Alcoholic Drinks",
        "Cleaning Goods": "Cleaning",
        "Coles Finest": "Miscellaneous",
        "Coles Made Easy Range": "Miscellaneous",
        "Crackers & Rice Cakes": "Snacks",
        "Cream & Custard": "Dairy",
        "Dairy Desserts": "Dairy",
        "Dairy, Chilled & Frozen": "Miscellaneous",
        "Dairy, Eggs & Fridge": "Miscellaneous",
        "Deli": "Miscellaneous",
        "Deli Meats": "Meat",
        "Deli Packaged Meat": "Meat",
        "Deli Poultry": "Meat",
        "Deli Seafood": "Seafood",
        "Deliver More Range": "Miscellaneous",
        "Dietary & World Foods": "Pantry",
        "Dips & Pate": "Miscellaneous",
        "Dog & Puppy": "Pet",
        "Down Down": "Deals",
        "Easy School Night Dinners": "Miscellaneous",
        "Eggs": "Eggs",
        "Entertaining": "Miscellaneous",
        "Fish Food & Accessories": "Pet",
        "Free From": "Miscellaneous",
        "Fresh Pasta & Sauces": "Miscellaneous",
        "Fruit & Vegetables": "Miscellaneous",
        "Game": "Meat",
        "Garlic Bread & Pastry Sheets": "Bakery",
        "Grant Burge": "Alcoholic Drinks",
        "Gum, Mints & Lozenges": "Sweets",
        "Halal": "Meat",
        "Heinz": "Pantry",
        "Homewares": "Home and Garden",
        "Home and Garden": "Home and Garden",
        "Jacobs Creek": "Alcoholic Drinks",
        "Lamb": "Meat",
        "Liquorland": "Alcoholic Drinks",
        "Lollies & Licorice": "Sweets",
        "Long-Life Flavoured Milk": "Pantry",
        "Long-Life-Milk": "Dairy",
        "Low Carb & Low Sugar": "Miscellaneous",
        "Low-Mid Strength": "Alcoholic Drinks",
        "Lunchbox Snacks": "Snacks",
        "Meat & Seafood": "Miscellaneous",
        "Milk": "Dairy",
        "Mince": "Meat",
        "New Dairy": "Dairy",
        "Nuts & Dried Fruit": "Fruit",
        "Oat Milk": "Pantry",
        "Packaged Deli Meats": "Meat",
        "Packaged Salad": "Veg",
        "Pantry Items": "Pantry",
        "Personal & Baby Care": "Miscellaneous",
        "Pet": "Pet",
        "Pork": "Meat",
        "Poultry": "Meat",
        "Powdered Long Life Milk": "Dairy",
        "Pre-Made Platters": "Miscellaneous",
        "Prepared Vegetable": "Veg",
        "Ready To Eat": "Miscellaneous",
        "Ready To Eat Meals": "Miscellaneous",
        "Red Wine": "Alcoholic Drinks",
        "Rose": "Alcoholic Drinks",
        "Salad & Herbs": "Veg",
        "School Accessories & Lunchboxes": "Home and Garden",
        "School Breakfast": "Miscellaneous",
        "School Lunches": "Miscellaneous",
        "Seafood": "Seafood",
        "Small Pets": "Pet",
        "Snacks": "Snacks",
        "Soy Milk": "Pantry",
        "Specialty Brands": "Miscellaneous",
        "Spirits": "Alcoholic Drinks",
        "Vegan & Vegetarian": "Veg",
        "Vegetarian & Vegan": "Veg",
        "White Wine": "Alcoholic Drinks",
        "Clothing & Accessories": "Clothing",
        "Health Foods & Diet": "Health Foods",
        "Health, Sports & Dietary Foods": "Health Foods",
        "Scoop & Weigh": "Health Foods",
        "Sports Nutrition": "Health Foods",
        "Cheese & Biscuits": "Miscellaneous",
        "Christmas": "Miscellaneous",
        "Christmas Decorations": "Miscellaneous",
        "Christmas Desserts & Chocolate": "Sweets",
        "Christmas Drinks & Liquor": "Alcoholic Drinks",
        "Christmas Entertaining": "Miscellaneous",
        "Christmas Gifting": "Miscellaneous",
        "Christmas Hams": "Meat",
        "Christmas Lunch": "Miscellaneous",
        "Condiments & Sauces": "Miscellaneous",
        "Creams, Custards & Ice Creams": "Dairy",
        "Cupboard Essentials": "Pantry",
        "Decorations & Tableware": "Miscellaneous",
        "Home & Garden": "Home and Garden",
        "Liquor Gifts": "Miscellaneous",
        "Meat Packaged": "Meat",
        "Meat, Fish & Poultry": "Miscellaneous",
        "Non-Alcoholic Drinks": "Non-Alcoholic Drinks",
        "Packaged Ham": "Meat",
        "Passover": "Miscellaneous",
        "Platters & Antipasto": "Miscellaneous",
        "Serving & Tableware": "Miscellaneous",
        "Soft Drinks & Mixers": "Miscellaneous",
        "South African": "Miscellaneous",
        "Sweets & Snacks": "Miscellaneous",
        "Antipasto": "Miscellaneous",
        "Bbq": "Miscellaneous",
        "Beer": "Alcoholic Drinks",
        "Canned Food": "Pantry",
        "Cheese & Desserts": "Miscellaneous",
        "Chilled Juice": "Non-Alcoholic Drinks",
        "Chilled Quiches & Pies": "Bakery",
        "Coffee & Tea": "Pantry",
        "Crackers, Dips & Pate": "Miscellaneous",
        "Dairy & Lactose Free": "Miscellaneous",
        "Deli Platter": "Miscellaneous",
        "Dips": "Miscellaneous",
        "Easy Breakfast": "Miscellaneous",
        "Easy Meals": "Miscellaneous",
        "Egg Free": "Miscellaneous",
        "Fat Free": "Miscellaneous",
        "Fodmap Friendly": "Miscellaneous",
        "Fresh Pasta & Noodles": "Miscellaneous",
        "Fruit": "Fruit",
        "Gluten Free": "Miscellaneous",
        "Gourmet Cheese": "Dairy",
        "Grab & Go Snacks": "Miscellaneous",
        "Grill": "Miscellaneous",
        "Hair & Skin Care": "Health and Beauty",
        "Ham": "Meat",
        "Hot Food": "Miscellaneous",
        "Hot Snacks & Sides": "Miscellaneous",
        "Indian Food & Meals": "Miscellaneous",
        "Italian Meals & Pasta": "Miscellaneous",
        "Kits & Meal Bases": "Miscellaneous",
        "Medicinal Care": "Health and Beauty",
        "Nescafe": "Pantry",
        "Nut Free": "Pantry",
        "Breakfast On The Go": "Miscellaneous"
    },
    "Iga": {
        "Baby": "Baby",
        "Bakery": "Bakery",
        "Dairy, Eggs And Fridge": "Miscellaneous",
        "Drinks": "Miscellaneous",
        "Front Of House": "Miscellaneous",
        "Frozen": "Freezer",
        "Fruit And Vegetable": "Fruit",
        "Grocery": "Miscellaneous",
        "Health And Beauty": "Health and Beauty",
        "Home and Garden": "Home and Garden",
        "Liquor": "Alcoholic Drinks",
        "Meat, Seafood And Deli": "Meat",
        "Pantry": "Pantry",
        "Pet": "Pet",
        "Other": "Miscellaneous"
    },
    "Woolworths": {
        "Air Fryer Ready": "Miscellaneous",
        "Almond & Other Nut Milks": "Pantry",
        "Almond Milk": "Pantry",
        "Baby": "Baby",
        "Baby Food": "Baby",
        "Baby Formula & Toddler Milk": "Baby",
        "Baby Furniture": "Baby",
        "Bake At Home": "Miscellaneous",
        "Batteries & Power": "Home and Garden",
        "Birds, Fish & Small Pets": "Pet",
        "Biscuit Multipacks": "Snacks",
        "Bon Bons & Partyware": "Home and Garden",
        "Bread Mix": "Bakery",
        "Cadbury": "Sweets",
        "Cakes & Biscuits": "Sweets",
        "Canned Tuna": "Meat",
        "Cat & Kitten": "Pet",
        "Champagne & Sparkling": "Alcoholic Drinks",
        "Cheese Slices & Blocks": "Dairy",
        "Chicken": "Meat",
        "Chips Multi-Pack": "Snacks",
        "Chocolate Bites": "Sweets",
        "Chocolate Sharing": "Sweets",
        "Christmas Cards, Wrapping & Bags": "Miscellaneous",
        "Christmas Trees": "Miscellaneous",
        "Chutney & Relish": "Pantry",
        "Cleaning & Maintenance": "Cleaning",
        "Crumpets & Pancakes": "Miscellaneous",
        "Denture Care": "Health and Beauty",
        "Dinner": "Miscellaneous",
        "Dried Fruit": "Pantry",
        "Dried Herbs & Spices": "Spices",
        "Boys & Girls Socks": "Clothing",
        "Boys & Girls Underwear": "Clothing",
        "Clothing & Accessories": "Clothing",
        "Eggs, Butter & Margarine": "Miscellaneous",
        "Electronics": "Electronics",
        "Eerie Entertaining": "Miscellaneous",
        "Everyday Yoghurt": "Dairy",
        "Festive Hats & Accessories": "Miscellaneous",
        "Fetta & Goat'S Cheese": "Dairy",
        "Flour": "Pantry",
        "Footwear & Shoe Care": "Clothing",
        "Fresh Herbs, Garlic & Chillies": "Spices",
        "Frozen Dumplings": "Freezer",
        "Frozen Fruit": "Freezer",
        "Frozen Pies & Sausage Rolls": "Freezer",
        "Frozen Vegetables": "Freezer",
        "Full Cream Milk": "Dairy",
        "Garden Decorations": "Home and Garden",
        "Gifts": "Miscellaneous",
        "Gifts For Kids": "Miscellaneous",
        "Gluten Free Pasta": "Pantry",
        "Grated Cheese": "Dairy",
        "Greek Yoghurt & Natural Yoghurt": "Dairy",
        "Gum, Mints & Lozenges": "Sweets",
        "High Protein Yoghurt": "Dairy",
        "Home Brew": "Miscellaneous",
        "Honey": "Pantry",
        "Hosiery": "Clothing",
        "Indian & South Asian": "Miscellaneous",
        "Jam": "Pantry",
        "Kids Yoghurt": "Dairy",
        "Kitchen Appliances": "Home and Garden",
        "Lactose Free Milk": "Dairy",
        "Lamb": "Meat",
        "Lamb Mince": "Meat",
        "Lights & Animated Decor": "Home and Garden",
        "Lozenges": "Health and Beauty",
        "M&M'S": "Sweets",
        "Meal Kits": "Miscellaneous",
        "Men'S Body Sprays": "Health and Beauty",
        "Men'S Care": "Health and Beauty",
        "Men'S Clothing & Underwear": "Clothing",
        "Men'S Hair Care": "Health and Beauty",
        "Men'S Skin": "Health and Beauty",
        "Men'S Socks": "Clothing",
        "Mexican": "Miscellaneous",
        "Microwave Ready": "Miscellaneous",
        "Middle Eastern": "Miscellaneous",
        "Muesli Bars & Snack Bars": "Snacks",
        "Nappies": "Health and Beauty",
        "Oral Care": "Health and Beauty",
        "Pancake Mix": "Pantry",
        "Parmesan & Italian Cheese": "Dairy",
        "Pasta Sheets": "Pantry",
        "Peanut Butter": "Pantry",
        "Period & Continence Care": "Health and Beauty",
        "Pest Control": "Home and Garden",
        "Pet": "Pet",
        "Pies, Pastries & Quiches": "Snacks",
        "Pink Moscato & Sweet Reds": "Alcoholic Drinks",
        "Pizza Bases": "Freezer",
        "Poultry, Meat & Seafood": "Meat",
        "Ready Made Cookies & Donuts": "Snacks",
        "Ready Made Desserts": "Sweets",
        "Red Wine": "Alcoholic Drinks",
        "Red Wine Cans": "Alcoholic Drinks",
        "Reese'S": "Snacks",
        "Rice & Bread": "Miscellaneous",
        "Ricotta, Cottage & Cream Cheese": "Miscellaneous",
        "Sauces & Condiments": "Pantry",
        "Savoury Spread": "Pantry",
        "Security & Smart Home": "Home and Garden",
        "Skim & Reduced Fat Milk": "Dairy",
        "Sliced Cheese": "Dairy",
        "Snacking": "Snacks",
        "Snacking Cheese": "Miscellaneous",
        "Sparkling Ros\u00e9": "Alcoholic Drinks",
        "Sparkling Sweet Wine": "Alcoholic Drinks",
        "Spice & Seasonings": "Spices",
        "Spirits": "Alcoholic Drinks",
        "Stationery": "Home and Garden",
        "Sweet Chilli & Hot Sauce": "Pantry",
        "Table & Hanging Decorations": "Miscellaneous",
        "Tableware & Partyware": "Miscellaneous",
        "Tea": "Pantry",
        "Tea & Coffee": "Pantry",
        "Teeth Whitening": "Health and Beauty",
        "The Natural Confectionery Co.": "Sweets",
        "Trees & Decorations": "Miscellaneous",
        "Umbrellas": "Home and Garden",
        "Vinegar": "Pantry",
        "Water": "Pantry",
        "White Blends": "Miscellaneous",
        "White Wine": "Alcoholic Drinks",
        "White Wine Cans": "Alcoholic Drinks",
        "Women'S Clothing & Underwear": "Clothing",
        "Women'S Hair Removal": "Health and Beauty",
        "Women'S Socks": "Clothing",
        "Yoghurt": "Dairy",
        "Antipasto": "Non-Alcoholic Drinks",
        "Asian Ready Meals": "Non-Alcoholic Drinks",
        "Assorted Desserts": "Sweets",
        "Assorted Frozen Desserts": "Sweets",
        "Avocados": "Fruit",
        "Bananas": "Fruit",
        "Beer, Wine & Spirits": "Alcoholic Drinks",
        "Berries & Cherries": "Fruit",
        "Berries & Tropical": "Fruit",
        "Board Games & Puzzles": "Non-Alcoholic Drinks",
        "Bones, Joints & Muscle Health": "Health and Beauty",
        "Brain & Heart": "Health and Beauty",
        "Bread Rolls": "Bakery",
        "Broccoli, Cauliflower & Cabbage": "Veg",
        "Cake & Dessert Mix": "Sweets",
        "Cakes & Cheesecakes": "Bakery",
        "Canned Soup & Soup Ingredients": "Pantry",
        "Cask Wine": "Alcoholic Drinks",
        "Cc'S": "Snacks",
        "Children'S Health": "Health and Beauty",
        "Chilled Asian": "Freezer",
        "Chilled Water": "Non-Alcoholic Drinks",
        "Chips Single Pack": "Snacks",
        "Christmas Pork, Lamb & Turkey": "Meat",
        "Cider": "Alcoholic Drinks",
        "Cleansers & Toners": "Health and Beauty",
        "Coca-Cola Zero Sugar": "Non-Alcoholic Drinks",
        "Cold, Flu & Allergies": "Health and Beauty",
        "Coleslaw": "Miscellaneous",
        "Connoisseur": "Freezer",
        "Corn Chips & Salsa": "Miscellaneous",
        "Cream": "Dairy",
        "Crumbed Chicken & Fish": "Miscellaneous",
        "Custards, Creams & Egg Nog": "Dairy",
        "Darrell Lea": "Sweets",
        "Decorations & Festive Dried Fruits": "Miscellaneous",
        "Deli Specialties": "Meat",
        "Digestion & Probiotics": "Health and Beauty",
        "Digestive Health": "Health and Beauty",
        "Dolls & Action Figures": "Miscellaneous",
        "Doritos": "Snacks",
        "Drinks & Powders": "Non-Alcoholic Drinks",
        "Dumplings": "Miscellaneous",
        "Education & Learning": "Miscellaneous",
        "Educational & Early Learning": "Miscellaneous",
        "Entertaining": "Miscellaneous",
        "European, Uk & Irish": "Miscellaneous",
        "Face Masks & Patches": "Health and Beauty",
        "Face Moisturisers": "Health and Beauty",
        "Fatigue, Stress & Sleep": "Health and Beauty",
        "Flavouring, Essence & Food Colouring": "Miscellaneous",
        "Fortified & Cask Wine": "Alcoholic Drinks",
        "Fragrance": "Health and Beauty",
        "Fresh Pasta & Sauces": "Miscellaneous",
        "Frozen Desserts": "Freezer",
        "Frozen Yoghurt": "Freezer",
        "Garlic, Chillies & Spices": "Spices",
        "Gelato & Sorbet": "Freezer",
        "Gluten Free Bakery": "Bakery",
        "Halloween": "Miscellaneous",
        "Health & Safety": "Miscellaneous",
        "Health & Wellness": "Health and Beauty",
        "Health Meal Options": "Health Foods",
        "Heinz": "Miscellaneous",
        "Ice Cream": "Freezer",
        "Ice Cream & Toppings": "Freezer",
        "Ice Cream Cakes": "Freezer",
        "Ice Cream Cones, Syrups & Toppings": "Pantry",
        "Ice Cream Tubs": "Freezer",
        "Interactive Toys": "Miscellaneous",
        "Intimate Wellness": "Health and Beauty",
        "Italian Ready Meals": "Miscellaneous",
        "Jack Link'S": "Snacks",
        "Jatz": "Snacks",
        "Jelly": "Sweets",
        "Kefir": "Dairy",
        "Kettle": "Miscellaneous",
        "Kid'S Frozen Meals": "Freezer",
        "Kids Drinks": "Non-Alcoholic Drinks",
        "Kinder": "Sweets",
        "Lettuce, Kale & Leafy Greens": "Veg",
        "Life Savers": "Sweets",
        "Lindt": "Sweets",
        "Mars": "Sweets",
        "Melons & Mangoes": "Fruit",
        "Men'S Health": "Health and Beauty",
        "Model Building & Construction": "Miscellaneous",
        "Mount Franklin Lightly Sparkling": "Non-Alcoholic Drinks",
        "Muffins & Pastries": "Bakery",
        "Muffins & Scones": "Bakery",
        "Multi Vitamins": "Health and Beauty",
        "Muscat & Other Varieties": "Miscellaneous",
        "Mustard": "Pantry",
        "Non-Fiction": "Pantry",
        "Oil & Vinegar": "Pantry",
        "Omega-3": "Health and Beauty",
        "Organic": "Miscellaneous",
        "Organic Bakery": "Bakery",
        "Organic Beef": "Meat",
        "Organic Fruit": "Fruit",
        "Organic Loose": "Veg",
        "Party Tableware": "Miscellaneous",
        "Pastries & Desserts": "Bakery",
        "Peas, Beans, Corn & Asparagus": "Veg",
        "Pepsi": "Non-Alcoholic Drinks",
        "Peters": "Freezer",
        "Pickled Vegetables": "Pantry",
        "Platters": "Miscellaneous",
        "Popcorn": "Pantry",
        "Pork Mince": "Meat",
        "Port": "Alcoholic Drinks",
        "Potatoes & Pumpkins": "Veg",
        "Pregnancy & Family Planning": "Health and Beauty",
        "Pregnancy Care & Family Planning": "Health and Beauty",
        "Pregnancy Tests": "Health and Beauty",
        "Premium Ice Cream": "Freezer",
        "Premixed Drinks": "Non-Alcoholic Drinks",
        "Prepared Salads & Bowls": "Veg",
        "Pretzels & Jerky": "Snacks",
        "Pringles": "Snacks",
        "Ready Meals": "Miscellaneous",
        "Rice": "Pantry",
        "Rolls & Bagels": "Bakery",
        "Sakata": "Snacks",
        "Salad Kits": "Veg",
        "Sauces": "Pantry",
        "Sauces & Salsa": "Pantry",
        "Savoury Snacks": "Snacks",
        "Self Tanning": "Health and Beauty",
        "Serums": "Health and Beauty",
        "Sherry": "Alcoholic Drinks",
        "Skincare & Body": "Health and Beauty",
        "Skittles": "Snacks",
        "Smith'S": "Snacks",
        "Soft Drink Bottles": "Alcoholic Drinks",
        "Soft Plush Toys": "Miscellaneous",
        "Soups": "Miscellaneous",
        "Sourdough & Specialty Bread": "Bakery",
        "Soy Milk": "Pantry",
        "Sparkling Water": "Non-Alcoholic Drinks",
        "Spinach & Rocket": "Veg",
        "Sport & Outdoor Toys": "Home and Garden",
        "Spring Gardening - While Stocks Last": "Home and Garden",
        "Sprite": "Non-Alcoholic Drinks",
        "Still Water": "Non-Alcoholic Drinks",
        "Stir Fry & Soup Kits": "Miscellaneous",
        "Summer": "Miscellaneous",
        "Sun Protection": "Health and Beauty",
        "Sweets & Treats": "Sweets",
        "Thick & Creamy Yoghurt": "Dairy",
        "Tomato & Bbq Sauce": "Pantry",
        "Tortillas, Tacos & Chips": "Pantry",
        "Toy Cars & Trucks": "Miscellaneous",
        "Toys": "Miscellaneous",
        "Toys & Games": "Miscellaneous",
        "Toys & Playtime": "Miscellaneous",
        "Twisties": "Snacks",
        "Vitamins": "Health and Beauty",
        "Wok & Pan": "Miscellaneous",
        "Women'S Health": "Health and Beauty",
        "Wraps & Flatbread": "Pantry",
        "Zucchini, Eggplant & Squash": "Veg"
    }
}