import os
import pprint
from products.models import Product

TRANSLATION_TABLE_PATH = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'product_name_translation_table.py')

def regenerate_translation_table():
    """
    Queries all products, builds a translation dictionary from their name variations,
    and overwrites the product_name_translation_table.py file.
    """
    translations = {}
    # Assuming product.name_variations is a JSONField or similar storing a list of names
    all_products = Product.objects.exclude(name_variations__isnull=True).exclude(name_variations__exact='[]')

    for product in all_products:
        # Ensure name_variations is a list
        variations = product.name_variations if isinstance(product.name_variations, list) else []
        for variation in variations:
            if variation.lower() != product.name.lower():
                translations[variation] = product.name

    file_content = (
        "# This file is auto-generated by the regenerate_translation_table utility.\n"
        "# Do not edit manually.\n\n"
        f"PRODUCT_NAME_TRANSLATIONS = {pprint.pformat(translations)}\n"
    )

    with open(TRANSLATION_TABLE_PATH, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print(f"Successfully regenerated translation table with {len(translations)} entries.")
