import os
import pprint
from products.models import Product

TRANSLATION_TABLE_PATH = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'product_name_translation_table.py')

def regenerate_translation_table():
    """
    Queries all products, builds a translation dictionary from their name variations,
    and overwrites the product_name_translation_table.py file.
    """
    translations = {}
    # Get all products and filter in Python, as querying for empty JSONField lists can be unreliable.
    all_products = Product.objects.all()

    for product in all_products:
        # Ensure name_variations is a non-empty list before processing
        if not product.name_variations or not isinstance(product.name_variations, list):
            continue

        for variation_tuple in product.name_variations:
            # variation_tuple is expected to be (name, store)
            if isinstance(variation_tuple, (list, tuple)) and len(variation_tuple) > 0:
                variation_name = variation_tuple[0]
                if variation_name.lower() != product.name.lower():
                    translations[variation_name] = product.name

    file_content = (
        "# This file is auto-generated by the regenerate_translation_table utility.\n"
        "# Do not edit manually.\n\n"
        f"PRODUCT_NAME_TRANSLATIONS = {pprint.pformat(translations)}\n"
    )

    with open(TRANSLATION_TABLE_PATH, 'w', encoding='utf-8') as f:
        f.write(file_content)

    print(f"Successfully regenerated translation table with {len(translations)} entries.")
