# Generated by Django 5.2.4 on 2026-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BargainStats",
            fields=[
                (
                    "key",
                    models.CharField(
                        help_text="The unique key for the statistic (e.g., 'bargain_stats').",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="The pre-calculated statistical data."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp when the statistic was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bargain Stats",
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
            ],
        ),
    ]
