# Generated by Django 5.2.4 on 2025-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.TextField()),
                (
                    "pages",
                    models.JSONField(
                        default=list,
                        help_text='A list of page identifiers where this FAQ should appear (e.g., ["home", "substitutes"])',
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQs",
            },
        ),
    ]
