# Generated by Django 5.2.4 on 2025-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "page",
                    models.CharField(
                        help_text="Identifier for the page this FAQ belongs to (e.g., 'home', 'about').",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQs",
                "unique_together": {("question", "page")},
            },
        ),
    ]
