# Generated by Django 5.2.4 on 2025-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="faq",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="faq",
            name="pages",
            field=models.JSONField(
                default=list,
                help_text='A list of page identifiers where this FAQ should appear (e.g., ["home", "substitutes"])',
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name="faq",
            name="page",
        ),
    ]
