# Generated by Django 5.2.4 on 2025-12-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0002_bargainstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField()),
            ],
        ),
    ]
