# Generated by Django 5.2.4 on 2026-01-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_management", "0003_systemsetting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
