# Generated by Django 5.2.4 on 2025-08-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the parent company.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category, e.g., 'Fruit & Vegetables'.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly version of the name, e.g., 'fruit-vegetables'.",
                        max_length=120,
                    ),
                ),
                (
                    "store_category_id",
                    models.CharField(
                        blank=True,
                        help_text="The category ID from the store's website, if available.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The parent category, if this is a subcategory.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="companies.category",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The company that this category belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("slug", "company")},
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The specific name of the store, e.g., 'IGA Cannington' or 'Coles National'.",
                        max_length=100,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="The base URL of the specific store, if applicable.",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The parent company that owns this store.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "company")},
            },
        ),
    ]
