# Generated by Django 5.2.4 on 2025-09-23 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the parent company.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category, e.g., 'Fruit & Vegetables'.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly version of the name, e.g., 'fruit-vegetables'.",
                        max_length=120,
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        blank=True,
                        help_text="The category ID from the store's website, if available.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The parent categories of this category.",
                        related_name="subcategories",
                        to="companies.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("CLOSE", "Close Relation"),
                            ("DISTANT", "Distant Relation"),
                        ],
                        help_text="The type or strength of the link between the two categories.",
                        max_length=10,
                    ),
                ),
                (
                    "category_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_a",
                        to="companies.category",
                    ),
                ),
                (
                    "category_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_b",
                        to="companies.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to categories in other companies with a defined relationship type.",
                through="companies.CategoryLink",
                to="companies.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="company",
            field=models.ForeignKey(
                help_text="The company that this category belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="companies.company",
            ),
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="The unique identifier for the division from the company's system (e.g., Coles brand ID).",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of the division (e.g., 'Coles Supermarkets', 'SUPERMARKETS').",
                        max_length=100,
                    ),
                ),
                (
                    "store_finder_id",
                    models.CharField(
                        blank=True,
                        help_text="A specific ID for the division used in store finder systems.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The parent company that owns this division.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(
                        help_text="The specific name of the store, e.g., 'IGA Cannington' or 'Coles National'.",
                        max_length=255,
                    ),
                ),
                (
                    "store_id",
                    models.CharField(
                        db_index=True,
                        help_text="The unique identifier for the store from the company's own system.",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True if the store is currently being scraped.",
                    ),
                ),
                (
                    "is_online_shopable",
                    models.BooleanField(
                        default=False,
                        help_text="True if the store has a functioning online shop that can be scraped.",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The contact phone number for the store.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        blank=True,
                        help_text="The first line of the store's address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="The second line of the store's address.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "suburb",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The suburb where the store is located.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The state or territory of the store.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        help_text="The postcode of the store.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="The latitude of the store's location.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="The longitude of the store's location.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "trading_hours",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object storing the store's trading hours.",
                        null=True,
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object storing a list of store facilities.",
                        null=True,
                    ),
                ),
                (
                    "is_trading",
                    models.BooleanField(
                        blank=True,
                        help_text="Indicates if the store is currently trading.",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the stores details were last updated.",
                    ),
                ),
                (
                    "last_scraped",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the store's products were last scraped.",
                        null=True,
                    ),
                ),
                (
                    "retailer_store_id",
                    models.CharField(
                        blank=True,
                        help_text="The retailer-specific identifier for the store, if available.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The contact email for the store.",
                        max_length=254,
                    ),
                ),
                (
                    "online_shop_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL for the store's online shopping portal.",
                        max_length=255,
                    ),
                ),
                (
                    "store_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL for the store's website.",
                        max_length=255,
                    ),
                ),
                (
                    "ecommerce_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL for the store's e-commerce platform.",
                        max_length=255,
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        blank=True,
                        help_text="The unique identifier for the store record from the IGA system.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="The status of the store (e.g., 'Active').",
                        max_length=50,
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        blank=True,
                        help_text="The type of the store (e.g., 'Regular').",
                        max_length=50,
                    ),
                ),
                (
                    "site_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the site from the IGA system.",
                        max_length=50,
                    ),
                ),
                (
                    "shopping_modes",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object storing a list of available shopping modes.",
                        null=True,
                    ),
                ),
                (
                    "available_customer_service_types",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object storing a list of available customer service types.",
                        null=True,
                    ),
                ),
                (
                    "alcohol_availability",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object storing a list of available alcohol types.",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The parent company that owns this store.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="companies.company",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific division of the store.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="companies.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
            },
        ),
        migrations.CreateModel(
            name="StoreGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("DIVERGENCE_DETECTED", "Divergence Detected"),
                        ],
                        default="HEALTHY",
                        max_length=25,
                    ),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambassador_for_group",
                        to="companies.store",
                    ),
                ),
                (
                    "candidates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="candidate_for_groups",
                        to="companies.store",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_groups",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="companies.storegroup",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_membership",
                        to="companies.store",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="categorylink",
            constraint=models.UniqueConstraint(
                fields=("category_a", "category_b"), name="unique_category_link"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "company")},
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together={("name", "company")},
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("company", "store_id")},
        ),
        migrations.AlterUniqueTogether(
            name="storegroupmembership",
            unique_together={("store", "group")},
        ),
    ]
