# Generated by Django 5.2.4 on 2026-06-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the parent company.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "image_url_template",
                    models.TextField(
                        blank=True,
                        help_text="URL template for constructing product image URLs. Use {sku} as a placeholder.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Postcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(db_index=True, max_length=10, unique=True),
                ),
                ("state", models.CharField(max_length=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                "ordering": ["postcode"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category, e.g., 'Fruit & Vegetables'.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly version of the name, e.g., 'fruit-vegetables'.",
                        max_length=120,
                    ),
                ),
                (
                    "category_id",
                    models.CharField(
                        blank=True,
                        help_text="The category ID from the store's website, if available.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The parent categories of this category.",
                        related_name="subcategories",
                        to="companies.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("CLOSE", "Close Relation"),
                            ("DISTANT", "Distant Relation"),
                        ],
                        help_text="The type or strength of the link between the two categories.",
                        max_length=10,
                    ),
                ),
                (
                    "category_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_a",
                        to="companies.category",
                    ),
                ),
                (
                    "category_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_b",
                        to="companies.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to categories in other companies with a defined relationship type.",
                through="companies.CategoryLink",
                to="companies.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="company",
            field=models.ForeignKey(
                help_text="The company that this category belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="companies.company",
            ),
        ),
        migrations.CreateModel(
            name="PrimaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "price_comparison_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores price comparison data between companies.",
                        null=True,
                    ),
                ),
                (
                    "sub_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="parent_categories",
                        to="companies.primarycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Primary Categories",
            },
        ),
        migrations.CreateModel(
            name="PillarPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("hero_title", models.CharField(max_length=200)),
                ("introduction_paragraph", models.TextField()),
                (
                    "primary_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pillar_pages",
                        to="companies.primarycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary category that this category belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="companies.primarycategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorylink",
            constraint=models.UniqueConstraint(
                fields=("category_a", "category_b"), name="unique_category_link"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("slug", "company")},
        ),
    ]
