# Generated by Django 5.2.4 on 2025-08-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="last_scraped_products",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the store's products were last scraped.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when the stores details were last updated.",
            ),
        ),
    ]
