# Generated by Django 5.2.4 on 2025-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_popular",
            field=models.BooleanField(
                default=False,
                help_text="Flag to indicate if this category is considered popular.",
            ),
        ),
    ]
