# Generated by Django 5.2.4 on 2025-09-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="equivalent_categories",
        ),
        migrations.CreateModel(
            name="CategoryEquivalence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("EQ", "Equivalent"), ("SUB", "Is Subset Of")],
                        help_text="'Equivalent' is a symmetrical relationship. 'Is Subset Of' is a directed relationship (e.g., from_category is a subset of to_category).",
                        max_length=3,
                    ),
                ),
                (
                    "from_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_equivalences",
                        to="companies.category",
                    ),
                ),
                (
                    "to_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_equivalences",
                        to="companies.category",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_category", "to_category")},
            },
        ),
        migrations.AddField(
            model_name="category",
            name="equivalences",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to categories in other companies with a defined relationship type.",
                through="companies.CategoryEquivalence",
                to="companies.category",
            ),
        ),
    ]
