# Generated by Django 5.2.4 on 2025-11-05 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storegroup",
            name="anchor",
        ),
        migrations.AddField(
            model_name="storegroup",
            name="anchor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anchor_for_group",
                to="companies.store",
            ),
        ),
    ]
