# Generated by Django 5.2.4 on 2025-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="equivalent_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to categories in other companies that are considered equivalent.",
                to="companies.category",
            ),
        ),
    ]
