# Generated by Django 5.2.4 on 2025-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarycategory",
            name="sub_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="parent_categories",
                to="companies.primarycategory",
            ),
        ),
    ]
