# Generated by Django 5.1.6 on 2025-08-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="category_hierarchy_id",
        ),
    ]
