# Generated by Django 5.2.4 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="image_url_template",
            field=models.TextField(
                blank=True,
                help_text="URL template for constructing product image URLs. Use {sku} as a placeholder.",
                null=True,
            ),
        ),
    ]
