# Generated by Django 5.2.4 on 2025-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Postcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode", models.CharField(db_index=True, max_length=10)),
                ("locality", models.CharField(db_index=True, max_length=100)),
                ("state", models.CharField(max_length=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                "ordering": ["postcode", "locality"],
                "unique_together": {("postcode", "locality", "state")},
            },
        ),
    ]
