# Generated by Django 5.2.4 on 2025-11-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PillarPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("hero_title", models.CharField(max_length=200)),
                ("introduction_paragraph", models.TextField()),
                ("image_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "primary_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pillar_pages",
                        to="companies.primarycategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
