# Generated by Django 5.1.6 on 2025-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"verbose_name": "Store", "verbose_name_plural": "Stores"},
        ),
        migrations.RemoveField(
            model_name="store",
            name="address",
        ),
        migrations.RemoveField(
            model_name="store",
            name="base_url",
        ),
        migrations.RemoveField(
            model_name="store",
            name="city",
        ),
        migrations.AddField(
            model_name="store",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                help_text="The first line of the store's address.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="The second line of the store's address.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text="The specific brand of the store, e.g., 'Coles Supermarkets'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="country",
            field=models.CharField(
                default="Australia",
                help_text="The country where the store is located.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(
                blank=True, help_text="A longer description of the store, if available."
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="division",
            field=models.CharField(
                blank=True,
                help_text="The division the store belongs to, e.g., 'Supermarkets'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="facilities",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object storing a list of store facilities.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="fax_number",
            field=models.CharField(
                blank=True,
                help_text="The contact fax number for the store.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="is_trading",
            field=models.BooleanField(
                blank=True,
                help_text="Indicates if the store is currently trading.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="The latitude of the store's location.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="The longitude of the store's location.",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="online_shop_url",
            field=models.URLField(
                blank=True,
                help_text="The URL for the store's online shopping portal.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="The contact phone number for the store.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="suburb",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The suburb where the store is located.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="trading_hours",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object storing the store's trading hours.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(
                help_text="The specific name of the store, e.g., 'IGA Cannington' or 'Coles National'.",
                max_length=255,
            ),
        ),
    ]
