# Generated by Django 5.2.4 on 2025-09-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="equivalences",
        ),
        migrations.DeleteModel(
            name="CategoryEquivalence",
        ),
    ]
