# Generated by Django 5.1.6 on 2025-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.CharField(
                blank=True, help_text="The street address of the store.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The city where the store is located.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The state or territory of the store.",
                max_length=50,
            ),
        ),
    ]
