# Generated by Django 5.2.4 on 2025-11-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_store_scheduled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="address_line_2",
        ),
        migrations.RemoveField(
            model_name="store",
            name="alcohol_availability",
        ),
        migrations.RemoveField(
            model_name="store",
            name="available_customer_service_types",
        ),
        migrations.RemoveField(
            model_name="store",
            name="ecommerce_url",
        ),
        migrations.RemoveField(
            model_name="store",
            name="email",
        ),
        migrations.RemoveField(
            model_name="store",
            name="facilities",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_online_shopable",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_trading",
        ),
        migrations.RemoveField(
            model_name="store",
            name="online_shop_url",
        ),
        migrations.RemoveField(
            model_name="store",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="store",
            name="record_id",
        ),
        migrations.RemoveField(
            model_name="store",
            name="scheduled_at",
        ),
        migrations.RemoveField(
            model_name="store",
            name="shopping_modes",
        ),
        migrations.RemoveField(
            model_name="store",
            name="site_id",
        ),
        migrations.RemoveField(
            model_name="store",
            name="status",
        ),
        migrations.RemoveField(
            model_name="store",
            name="store_type",
        ),
        migrations.RemoveField(
            model_name="store",
            name="store_url",
        ),
        migrations.RemoveField(
            model_name="store",
            name="trading_hours",
        ),
    ]
