# Generated by Django 5.2.4 on 2025-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_storegroup_ambassador_storegroup_anchor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storegroup",
            name="candidates",
        ),
    ]
