# Generated by Django 5.2.4 on 2025-09-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_storegroup_storegroupmembership"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="last_scraped_products",
            new_name="last_scraped",
        ),
        migrations.RemoveField(
            model_name="storegroupmembership",
            name="last_scraped_as_ambassador",
        ),
        migrations.AddField(
            model_name="storegroup",
            name="ambassador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ambassador_for_group",
                to="companies.store",
            ),
        ),
        migrations.AddField(
            model_name="storegroup",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, related_name="candidate_for_groups", to="companies.store"
            ),
        ),
    ]
