# Generated by Django 5.2.4 on 2025-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_store_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="address_line_1",
            field=models.CharField(
                blank=True,
                help_text="The first line of the store's address.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="The second line of the store's address.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="postcode",
            field=models.CharField(
                blank=True,
                help_text="The postcode of the store.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="state",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The state or territory of the store.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="suburb",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The suburb where the store is located.",
                max_length=100,
                null=True,
            ),
        ),
    ]
