# Generated by Django 5.2.4 on 2025-09-14 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_category_equivalences_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("MATCH", "Match"),
                            ("CLOSE", "Close Relation"),
                            ("DISTANT", "Distant Relation"),
                        ],
                        help_text="The type or strength of the link between the two categories.",
                        max_length=10,
                    ),
                ),
                (
                    "category_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_a",
                        to="companies.category",
                    ),
                ),
                (
                    "category_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_b",
                        to="companies.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="links",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links to categories in other companies with a defined relationship type.",
                through="companies.CategoryLink",
                to="companies.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorylink",
            constraint=models.UniqueConstraint(
                fields=("category_a", "category_b"), name="unique_category_link"
            ),
        ),
    ]
