# Generated by Django 5.2.4 on 2025-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_category_is_popular"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="popular_categories", to="companies.category"
                    ),
                ),
            ],
        ),
    ]
