# Generated by Django 5.2.4 on 2025-08-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_category_unique_together_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="store_category_id",
            field=models.CharField(
                blank=True,
                help_text="The category ID from the store's website, if available.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
