# Generated by Django 5.2.4 on 2025-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_image_url_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="needs_rescraping",
            field=models.BooleanField(
                default=False,
                help_text="Flagged by the system for a high-priority re-scrape.",
            ),
        ),
    ]
