# Generated by Django 5.2.4 on 2025-08-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_store_last_scraped_products_alter_store_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_online_shopable",
            field=models.BooleanField(
                default=False,
                help_text="True if the store has a functioning online shop that can be scraped.",
            ),
        ),
    ]
