# Generated by Django 5.1.6 on 2025-08-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_store_options_remove_store_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="email",
            field=models.EmailField(
                blank=True, help_text="The contact email for the store.", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="retailer_store_id",
            field=models.CharField(
                blank=True,
                help_text="The retailer-specific identifier for the store, if available.",
                max_length=50,
            ),
        ),
    ]
