# Generated by Django 5.2.4 on 2025-09-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_postcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postcode",
            options={"ordering": ["postcode"]},
        ),
        migrations.AlterUniqueTogether(
            name="postcode",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="postcode",
            name="postcode",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name="postcode",
            name="locality",
        ),
    ]
