# Generated by Django 5.2.4 on 2025-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_pillarpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="primarycategory",
            name="price_comparison_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores price comparison data between companies.",
                null=True,
            ),
        ),
    ]
