# Generated by Django 5.2.4 on 2025-09-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_store_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="retailer_store_id",
            field=models.CharField(
                blank=True,
                help_text="The retailer-specific identifier for the store, if available.",
                max_length=50,
                null=True,
            ),
        ),
    ]
