# Generated by Django 5.1.6 on 2025-08-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_store_is_online_shopable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="name",
            new_name="store_name",
        ),
    ]
