# Generated by Django 5.2.4 on 2025-11-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_primarycategory_price_comparison_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pillarpage",
            name="image_path",
        ),
    ]
