# Generated by Django 5.2.4 on 2025-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_rename_last_scraped_products_store_last_scraped_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storegroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("DIVERGENCE_DETECTED", "Divergence Detected"),
                ],
                default="HEALTHY",
                max_length=25,
            ),
        ),
    ]
