# Generated by Django 5.2.4 on 2025-10-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_popularcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_popular",
        ),
    ]
