# Generated by Django 5.1.6 on 2025-08-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_store_email_store_retailer_store_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="store",
            name="country",
        ),
        migrations.RemoveField(
            model_name="store",
            name="description",
        ),
        migrations.RemoveField(
            model_name="store",
            name="fax_number",
        ),
    ]
