# Generated by Django 5.2.4 on 2025-11-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_store_needs_rescraping"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time when the store was last scheduled for scraping.",
                null=True,
            ),
        ),
    ]
