# Generated by Django 5.1.6 on 2025-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_store_brand_remove_store_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="alcohol_availability",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object storing a list of available alcohol types.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="available_customer_service_types",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object storing a list of available customer service types.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="category_hierarchy_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the category hierarchy from the IGA system.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="ecommerce_url",
            field=models.URLField(
                blank=True,
                help_text="The URL for the store's e-commerce platform.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time when the store was last updated.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="record_id",
            field=models.CharField(
                blank=True,
                help_text="The unique identifier for the store record from the IGA system.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="shopping_modes",
            field=models.JSONField(
                blank=True,
                help_text="A JSON object storing a list of available shopping modes.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="site_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the site from the IGA system.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="The status of the store (e.g., 'Active').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                blank=True,
                help_text="The type of the store (e.g., 'Regular').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_url",
            field=models.URLField(
                blank=True, help_text="The URL for the store's website.", max_length=255
            ),
        ),
    ]
