# Generated by Django 5.2.4 on 2025-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_store_scheduled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storegroup",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="storegroup",
            name="status",
        ),
    ]
