# Generated by Django 5.1.6 on 2025-08-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_store_alcohol_availability_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="division",
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="The name of the brand.", max_length=100, unique=True
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        help_text="The unique identifier for the brand.",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "store_finder_id",
                    models.CharField(
                        blank=True,
                        help_text="The store finder ID for the brand.",
                        max_length=100,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="The parent company that owns this brand.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific brand of the store.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="companies.brand",
            ),
        ),
    ]
