# Generated by Django 5.2.4 on 2025-11-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_remove_storegroup_is_active_remove_storegroup_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "verbose_name_plural": "Primary Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary category that this category belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="companies.primarycategory",
            ),
        ),
    ]
