# Generated by Django 5.2.4 on 2025-11-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_primarycategory_category_primary_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PopularCategory",
        ),
    ]
