import abc
from pprint import pformat

class BaseTranslationTableGenerator(abc.ABC):
    """
    An abstract base class for generating translation table files.

    This class provides the core functionality to generate a Python file
    containing a translation dictionary. Subclasses are expected to

    implement the `generate_translation_dict` method to provide the
    specific data to be written.
    """

    def __init__(self, output_path: str, variable_name: str):
        """
        Initializes the generator with the output path and the name for the
        dictionary variable.

        Args:
            output_path: The absolute path to the output .py file.
            variable_name: The name of the dictionary variable to be written
                           to the file (e.g., "PRODUCT_NAME_TRANSLATIONS").
        """
        self.output_path = output_path
        self.variable_name = variable_name

    @abc.abstractmethod
    def generate_translation_dict(self) -> dict:
        """
        Abstract method to be implemented by subclasses.

        This method should query the database and construct a dictionary
        representing the translation table.

        Returns:
            A dictionary containing the translation data.
        """
        pass

    def write_to_file(self, data: dict):
        """
        Writes the generated dictionary to the specified Python file.

        The output file will contain a header and the dictionary assigned
        to the variable name specified during initialization.
        """
        print(f"Writing translation table to {self.output_path}...")
        content = (
            f"# This file is auto-generated by {self.__class__.__name__}.\n"
            f"# Do not edit manually.\n\n"
            f"{self.variable_name} = {pformat(data)}\n"
        )
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print("Done.")

    def run(self):
        """
        Orchestrates the generation and writing of the translation table file.
        """
        print(f"Running {self.__class__.__name__}...")
        translation_dict = self.generate_translation_dict()
        self.write_to_file(translation_dict)
