# Generated by Django 5.2.4 on 2025-09-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_price_options_remove_price_scraped_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-scraped_date"]},
        ),
    ]
