from django.urls import path, include
from rest_framework_nested import routers

from users.views.cart_viewset import CartViewSet
from users.views.selected_store_list_viewset import SelectedStoreListViewSet
from users.views.cart_item_viewset import CartItemViewSet
from users.views.cart_optimization_view import CartOptimizationView
from users.views.cart_substitution_update_destroy_view import CartSubstitutionUpdateDestroyView
from .views.nearby_store_list_view import StoreListView

# The main router includes the top-level resources
router = routers.SimpleRouter()
router.register(r'carts', CartViewSet, basename='cart')
router.register(r'store-lists', SelectedStoreListViewSet, basename='storelist')

# A nested router for items within a cart
# This creates URLs like /carts/{cart_pk}/items/
carts_router = routers.NestedSimpleRouter(router, r'carts', lookup='cart')
carts_router.register(r'items', CartItemViewSet, basename='cart-items')

# Start with the URLs that are not being replaced by a ViewSet
urlpatterns = [
    path('stores/nearby/', StoreListView.as_view(), name='store-list'),
    path('cart/optimize/', CartOptimizationView.as_view(), name='cart-optimize'),
    path('cart-items/<int:cart_item_pk>/substitutions/<int:substitution_pk>/', CartSubstitutionUpdateDestroyView.as_view(), name='cart-substitution-detail'),
]

# Add the new, clean URLs generated by the routers
urlpatterns += [
    path('', include(router.urls)),
    path('', include(carts_router.urls)),
]
