# Generated by Django 5.2.4 on 2025-07-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the store, e.g., 'Coles', 'Woolworths'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="The base URL of the store's website.", max_length=255
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the category, e.g., 'Fruit & Vegetables'.",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="A URL-friendly version of the name, e.g., 'fruit-vegetables'.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional: The specific URL path for this category if it's not based on the slug.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The store this category belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("name", "store")},
            },
        ),
    ]
