# Generated by Django 5.2.4 on 2025-07-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent")},
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent category, if this is a subcategory.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="stores.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The store this category belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stores.store",
            ),
        ),
        migrations.RemoveField(
            model_name="category",
            name="url_path",
        ),
    ]
