import os
import json

def load_progress(PROGRESS_FILE, LAT_MIN, LAT_STEP, LON_MIN, LON_MAX, LON_STEP):
    """Loads the last processed coordinates from a file, handling rollover."""
    if os.path.exists(PROGRESS_FILE):
        try:
            with open(PROGRESS_FILE, 'r', encoding='utf-8') as f:
                progress = json.load(f)
                last_lat = progress.get('last_lat', LAT_MIN)
                last_lon = progress.get('last_lon', LON_MIN)

                # Round last_lat and last_lon to the nearest step to avoid floating point issues
                # This ensures they align with the values generated by drange
                rounded_last_lat = round(last_lat / LAT_STEP) * LAT_STEP
                rounded_last_lon = round(last_lon / LON_STEP) * LON_STEP

                if rounded_last_lon >= LON_MAX:
                    print(f"\nCompleted row for Lat: {rounded_last_lat}. Resuming on next latitude.")
                    return rounded_last_lat + LAT_STEP, LON_MIN
                else:
                    print(f"\nResuming from Lat: {rounded_last_lat}, Lon: {rounded_last_lon + LON_STEP}")
                    return rounded_last_lat, rounded_last_lon + LON_STEP
        except (json.JSONDecodeError, IOError):
            print(f"\nWarning: {PROGRESS_FILE} is corrupted or unreadable. Starting from the beginning.")
    return LAT_MIN, LON_MIN