# Generated by Django 5.2.4 on 2025-11-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The canonical (most common) name for this brand.",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True,
                        help_text="The normalized version of the brand name, used as the unique key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of all other raw names this brand has been seen as.",
                    ),
                ),
                (
                    "normalized_name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of normalized names from the name_variations list for faster lookups.",
                    ),
                ),
                (
                    "longest_inferred_prefix",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, null=True
                    ),
                ),
                (
                    "confirmed_official_prefix",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The full name of the product as seen in the store.",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_name_brand_size",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Normalized combination of name, brand, and size for uniqueness.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "normalized_name_brand_size_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of normalized strings for discovered variations.",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="The original, raw size string for the product (e.g., 'approx. 300g').",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sizes",
                    models.JSONField(
                        default=list,
                        help_text="A list of all size-related strings found for the product.",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The universal barcode (UPC/EAN) of the product.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "company_skus",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A dictionary of company names to a list of their SKUs for this product.",
                    ),
                ),
                (
                    "has_no_coles_barcode",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True if Coles has been scraped and no barcode was found.",
                    ),
                ),
                (
                    "image_url_pairs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of [company_name, image_url] tuples for this product.",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "brand_name_company_pairs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of [raw_brand_name, company_name] tuples for this product.",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        help_text="The categories this product belongs to.",
                        related_name="products",
                        to="companies.category",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the canonical ProductBrand entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.productbrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scraped_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "was_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "per_unit_price_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct_scrape", "Direct Scrape"),
                            ("inferred_group", "Inferred from Group"),
                        ],
                        default="direct_scrape",
                        help_text="How the price was obtained: from a direct scrape or inferred from a group ambassador.",
                        max_length=20,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="companies.store",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name"],
                "unique_together": {("product", "store")},
            },
        ),
        migrations.CreateModel(
            name="ProductSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LVL1", "Same brand, same product, different size."),
                            ("LVL2", "Same brand, similar product, similar size."),
                            ("LVL3", "Same category, semantic match."),
                            ("LVL4", "Linked category, semantic match."),
                        ],
                        db_index=True,
                        default="LVL3",
                        help_text="The classification of the substitution level based on heuristics.",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        help_text="Confidence score from 0.0 to 1.0, indicating the quality of the match.",
                    ),
                ),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_a",
                        to="products.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_b",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("product_a", "product_b")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other products that can be used as substitutes, ranked by a score.",
                through="products.ProductSubstitution",
                to="products.product",
            ),
        ),
        migrations.CreateModel(
            name="SuperCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="super_categories", to="companies.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Super Categories",
            },
        ),
        migrations.CreateModel(
            name="Bargain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargains",
                        to="companies.store",
                    ),
                ),
                (
                    "cheapest_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargain_as_cheapest",
                        to="products.price",
                    ),
                ),
                (
                    "most_expensive_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargain_as_most_expensive",
                        to="products.price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargain_records",
                        to="products.product",
                    ),
                ),
                (
                    "super_categories",
                    models.ManyToManyField(
                        blank=True, related_name="bargains", to="products.supercategory"
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "store")},
            },
        ),
    ]
