# Generated by Django 5.2.4 on 2025-08-22 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The full name of the product as seen in the store.",
                        max_length=255,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The brand of the product, e.g., 'Coles', 'Coca-Cola'.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sizes",
                    models.JSONField(
                        default=list,
                        help_text="A list of all size-related strings found for the product.",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The universal barcode (UPC/EAN) of the product.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("url", models.URLField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allergens", models.TextField(blank=True, null=True)),
                ("ingredients", models.TextField(blank=True, null=True)),
                (
                    "normalized_name_brand_size",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Normalized combination of name, brand, and size for uniqueness.",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        help_text="The categories this product belongs to.",
                        related_name="products",
                        to="companies.category",
                    ),
                ),
                (
                    "size_variants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products that are the same item but in a different size.",
                        to="products.product",
                    ),
                ),
                (
                    "substitute_goods",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional: Other products that can be used as substitutes.",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_product_id", models.CharField(db_index=True, max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The current price of the product.",
                        max_digits=10,
                    ),
                ),
                (
                    "was_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The previous price if the item is on special.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The price per standard unit (e.g., per 100g, per 1L).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        help_text="The standard unit for the unit_price, e.g., '100g', '1L'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the product was in stock at the time of scraping.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the latest price record for the product at this store.",
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="companies.store",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("barcode",),
                name="unique_barcode_if_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("normalized_name_brand_size__isnull", False)),
                fields=("normalized_name_brand_size",),
                name="unique_normalized_name_brand_size",
            ),
        ),
    ]
