# Generated by Django 5.2.4 on 2025-09-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The canonical (most common) name for this brand.",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True,
                        help_text="The normalized version of the brand name, used as the unique key.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of all other raw names this brand has been seen as.",
                    ),
                ),
                (
                    "normalized_name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of normalized names from the name_variations list for faster lookups.",
                    ),
                ),
                ("is_store_brand", models.BooleanField(default=False)),
                (
                    "parent_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandPrefix",
            fields=[
                (
                    "brand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="prefix_analysis",
                        serialize=False,
                        to="products.productbrand",
                    ),
                ),
                (
                    "longest_inferred_prefix",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, null=True
                    ),
                ),
                (
                    "confirmed_official_prefix",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, null=True
                    ),
                ),
                (
                    "brand_name_gs1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The full name of the product as seen in the store.",
                        max_length=255,
                    ),
                ),
                (
                    "name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of (name, store) tuples for discovered name variations.",
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The normalized version of the product name.",
                        max_length=255,
                    ),
                ),
                (
                    "normalized_name_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of just the normalized names from the name_variations list.",
                    ),
                ),
                (
                    "normalized_name_brand_size",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Normalized combination of name, brand, and size for uniqueness.",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "normalized_name_brand_size_variations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="A list of normalized strings for discovered variations.",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="The original, raw size string for the product (e.g., 'approx. 300g').",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sizes",
                    models.JSONField(
                        default=list,
                        help_text="A list of all size-related strings found for the product.",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The universal barcode (UPC/EAN) of the product.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "has_no_coles_barcode",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True if Coles has been scraped and no barcode was found.",
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("url", models.URLField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("allergens", models.TextField(blank=True, null=True)),
                ("ingredients", models.TextField(blank=True, null=True)),
                ("health_star_rating", models.FloatField(blank=True, null=True)),
                ("average_user_rating", models.FloatField(blank=True, null=True)),
                ("rating_count", models.IntegerField(blank=True, null=True)),
                (
                    "unit_of_sale",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dietary_and_lifestyle_tags",
                    models.JSONField(blank=True, default=list),
                ),
                ("is_age_restricted", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the canonical ProductBrand entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.productbrand",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        help_text="The categories this product belongs to.",
                        related_name="products",
                        to="companies.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The current price of the product.",
                        max_digits=10,
                    ),
                ),
                (
                    "was_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The previous price if the item is on special.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The price per standard unit (e.g., per 100g, per 1L).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        blank=True,
                        help_text="The standard unit for the unit_price, e.g., '100g', '1L'.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "per_unit_price_string",
                    models.CharField(
                        blank=True,
                        help_text="The raw string for the per unit price, e.g., '$1.68 per 100 g'.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "is_available",
                    models.BooleanField(
                        default=None,
                        help_text="Whether the product was in stock at the time of scraping.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the latest price record for the product at this store.",
                    ),
                ),
                ("scraped_date", models.DateField()),
                (
                    "normalized_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="companies.store",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_date"],
            },
        ),
        migrations.CreateModel(
            name="ProductSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LVL1", "Same brand, same product, different size."),
                            ("LVL2", "Same brand, similar product, similar size."),
                            ("LVL3", "Different brand, similar product, similar size."),
                            (
                                "LVL4",
                                "Different brand, similar product, different size.",
                            ),
                            ("LVL5", "Same category, semantic match."),
                            ("LVL6", "Linked category, semantic match."),
                        ],
                        db_index=True,
                        default="LVL4",
                        help_text="The classification of the substitution level based on heuristics.",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        db_index=True,
                        help_text="Confidence score from 0.0 to 1.0, indicating the quality of the match.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="unknown",
                        help_text="How this substitution was generated (e.g., 'heuristic_v1', 'manual').",
                        max_length=50,
                    ),
                ),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_a",
                        to="products.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_b",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("product_a", "product_b")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other products that can be used as substitutes, ranked by a score.",
                through="products.ProductSubstitution",
                to="products.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("barcode",),
                name="unique_barcode_if_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("normalized_name_brand_size__isnull", False)),
                fields=("normalized_name_brand_size",),
                name="unique_normalized_name_brand_size",
            ),
        ),
    ]
