# Generated by Django 5.2.4 on 2025-11-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_barcode_if_not_null_or_empty",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_normalized_name_brand_size",
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The universal barcode (UPC/EAN) of the product.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="normalized_name_brand_size",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized combination of name, brand, and size for uniqueness.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
