# Generated by Django 5.2.4 on 2025-09-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="per_unit_price_string",
            field=models.CharField(
                blank=True,
                help_text="The raw string for the per unit price, e.g., '$1.68 per 100 g'.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dietary_and_lifestyle_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="health_star_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_age_restricted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_of_sale",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
