# Generated by Django 5.2.4 on 2025-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size_variants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products that are the same item but in a different size.",
                related_name="_size_variants_set",
                to="products.product",
            ),
        ),
    ]
