# Generated by Django 5.2.4 on 2025-11-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url_pairs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of [company_name, image_url] tuples for this product.",
            ),
        ),
    ]
