# Generated by Django 5.2.4 on 2025-10-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="super_categories", to="companies.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Super Categories",
            },
        ),
        migrations.AddField(
            model_name="bargain",
            name="super_categories",
            field=models.ManyToManyField(
                blank=True, related_name="bargains", to="products.supercategory"
            ),
        ),
    ]
