# Generated by Django 5.2.4 on 2025-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsubstitution",
            name="source",
            field=models.CharField(
                default="unknown",
                help_text="How this substitution was generated (e.g., 'heuristic_v1', 'manual').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="productsubstitution",
            name="type",
            field=models.CharField(
                choices=[
                    ("SIZE", "Same product, different size"),
                    ("VARIANT", "Same brand, similar product"),
                    ("COMPETITOR", "Different brand, similar product"),
                    ("OTHER", "Other/Unknown"),
                ],
                db_index=True,
                default="OTHER",
                help_text="The classification of the substitution type based on heuristics.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productsubstitution",
            name="score",
            field=models.FloatField(
                db_index=True,
                help_text="Confidence score from 0.0 to 1.0, indicating the quality of the match.",
            ),
        ),
    ]
