# Generated by Django 5.2.4 on 2025-08-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_no_coles_barcode",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if Coles has been scraped and no barcode was found.",
            ),
        ),
    ]
