# Generated by Django 5.2.4 on 2025-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="is_available",
            field=models.BooleanField(
                default=None,
                help_text="Whether the product was in stock at the time of scraping.",
                null=True,
            ),
        ),
    ]
