# Generated by Django 5.2.4 on 2025-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_text",
            field=models.TextField(
                blank=True,
                help_text="A space-separated combination of name, brand, and size for full-text search.",
                null=True,
            ),
        ),
    ]
