# Generated by Django 5.2.4 on 2026-06-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpricesummary",
            name="iga_store_count",
        ),
    ]
