# Generated by Django 5.2.4 on 2025-08-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("barcode__isnull", False), models.Q(("barcode", ""), _negated=True)
                ),
                fields=("barcode",),
                name="unique_barcode_if_not_null_or_empty",
            ),
        ),
    ]
