# Generated by Django 5.2.4 on 2025-08-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="plu_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The Price Look-Up code for the product, typically for fresh produce.",
                max_length=10,
                null=True,
            ),
        ),
    ]
