# Generated by Django 5.2.4 on 2025-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                help_text="The size or quantity of the product, e.g., '500g', '1 Each'.",
                max_length=50,
                null=True,
            ),
        ),
    ]
