# Generated by Django 5.2.4 on 2025-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_name_variations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of just the normalized names from the name_variations list.",
            ),
        ),
    ]
