# Generated by Django 5.2.4 on 2025-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="url",
        ),
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
