# Generated by Django 5.2.4 on 2025-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("name", "brand", "size")},
        ),
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="nutritional_information",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="product",
            name="store",
        ),
    ]
