# Generated by Django 5.2.4 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url_pairs",
        ),
        migrations.AddField(
            model_name="product",
            name="aldi_image_url",
            field=models.URLField(
                blank=True,
                help_text="Full image URL for products from Aldi, which do not use a template.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
