# Generated by Django 5.2.4 on 2025-11-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_bargain",
        ),
    ]
