# Generated by Django 5.2.4 on 2025-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="source",
            field=models.CharField(
                choices=[
                    ("direct_scrape", "Direct Scrape"),
                    ("inferred_group", "Inferred from Group"),
                ],
                default="direct_scrape",
                help_text="How the price was obtained: from a direct scrape or inferred from a group ambassador.",
                max_length=20,
            ),
        ),
    ]
