# Generated by Django 5.2.4 on 2025-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsubstitution",
            name="type",
        ),
        migrations.AddField(
            model_name="productsubstitution",
            name="level",
            field=models.CharField(
                choices=[
                    ("LVL1", "Same brand, same product, different size."),
                    ("LVL2", "Same brand, similar product, similar size."),
                    ("LVL3", "Different brand, similar product, similar size."),
                    ("LVL4", "Different brand, similar product, different size."),
                ],
                db_index=True,
                default="LVL4",
                help_text="The classification of the substitution level based on heuristics.",
                max_length=20,
            ),
        ),
    ]
