# Generated by Django 5.2.4 on 2025-09-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_variants",
        ),
        migrations.RemoveField(
            model_name="product",
            name="substitute_goods",
        ),
        migrations.CreateModel(
            name="ProductSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(db_index=True)),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_a",
                        to="products.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions_b",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("product_a", "product_b")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products that can be substituted for this one, ranked by a score.",
                through="products.ProductSubstitution",
                to="products.product",
            ),
        ),
    ]
