# Generated by Django 5.2.4 on 2025-09-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_variants",
        ),
        migrations.DeleteModel(
            name="ProductSizeVariant",
        ),
    ]
