# Generated by Django 5.2.4 on 2025-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_price_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name_variations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of (name, store) tuples for discovered name variations.",
            ),
        ),
    ]
