# Generated by Django 5.2.4 on 2025-11-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_image_url_pairs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bargain",
            name="super_categories",
        ),
        migrations.DeleteModel(
            name="SuperCategory",
        ),
    ]
