# Generated by Django 5.2.4 on 2025-11-04 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_product_unique_barcode_if_not_null_or_empty_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-price_record__scraped_date"]},
        ),
        migrations.AlterUniqueTogether(
            name="pricerecord",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="bargain",
            name="percentage_difference",
        ),
        migrations.RemoveField(
            model_name="price",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="price",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="price",
            name="scraped_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="allergens",
        ),
        migrations.RemoveField(
            model_name="product",
            name="average_user_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="country_of_origin",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="dietary_and_lifestyle_tags",
        ),
        migrations.RemoveField(
            model_name="product",
            name="health_star_rating",
        ),
        migrations.RemoveField(
            model_name="product",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_age_restricted",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="unit_of_sale",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="is_store_brand",
        ),
        migrations.RemoveField(
            model_name="productsubstitution",
            name="source",
        ),
        migrations.AddField(
            model_name="pricerecord",
            name="scraped_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pricerecord",
            unique_together={
                (
                    "product",
                    "scraped_date",
                    "price",
                    "was_price",
                    "unit_price",
                    "unit_of_measure",
                    "per_unit_price_string",
                    "is_on_special",
                )
            },
        ),
    ]
