# Generated by Django 5.2.4 on 2025-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_has_no_coles_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="normalized_string_variations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of normalized strings for discovered variations.",
            ),
        ),
    ]
