# Generated by Django 5.2.4 on 2025-08-31 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_plu_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="plu_code",
        ),
    ]
