# Generated by Django 5.2.4 on 2025-09-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_price_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="is_on_special",
        ),
        migrations.RemoveField(
            model_name="price",
            name="per_unit_price_string",
        ),
        migrations.RemoveField(
            model_name="price",
            name="price",
        ),
        migrations.RemoveField(
            model_name="price",
            name="unit_of_measure",
        ),
        migrations.RemoveField(
            model_name="price",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="price",
            name="was_price",
        ),
        migrations.CreateModel(
            name="PriceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "was_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "per_unit_price_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_records",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Record",
                "verbose_name_plural": "Price Records",
                "unique_together": {
                    (
                        "product",
                        "price",
                        "was_price",
                        "unit_price",
                        "unit_of_measure",
                        "per_unit_price_string",
                        "is_on_special",
                    )
                },
            },
        ),
        migrations.AddField(
            model_name="price",
            name="price_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_entries",
                to="products.pricerecord",
            ),
        ),
    ]