# Generated by Django 5.2.4 on 2025-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productsubstitution_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubstitution",
            name="level",
            field=models.CharField(
                choices=[
                    ("LVL1", "Same brand, same product, different size."),
                    ("LVL2", "Same brand, similar product, similar size."),
                    ("LVL3", "Different brand, similar product, similar size."),
                    ("LVL4", "Different brand, similar product, different size."),
                    ("LVL5", "Same category, semantic match."),
                    ("LVL6", "Linked category, semantic match."),
                    ("LVL7", "Close-linked category, semantic match."),
                ],
                db_index=True,
                default="LVL4",
                help_text="The classification of the substitution level based on heuristics.",
                max_length=20,
            ),
        ),
    ]
