# Generated by Django 5.2.4 on 2025-11-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_url_pairs"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
