# Generated by Django 5.2.4 on 2025-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_primarycategory_price_comparison_data"),
        ("products", "0002_price_save_amount"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["store", "product"], name="products_pr_store_i_fcd987_idx"
            ),
        ),
    ]
