# Generated by Django 5.2.4 on 2025-09-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_size_variants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="substitutes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other products that can be used as substitutes, ranked by a score.",
                through="products.ProductSubstitution",
                to="products.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductSizeVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_variants_a",
                        to="products.product",
                    ),
                ),
                (
                    "product_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_variants_b",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product_a", "product_b")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size_variants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products that are the same item but in a different size.",
                through="products.ProductSizeVariant",
                to="products.product",
            ),
        ),
    ]
