# Generated by Django 5.2.4 on 2025-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_unique_together_product_allergens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this is the latest price record for the product at this store.",
            ),
        ),
    ]
