# Generated by Django 5.2.4 on 2025-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0002_product_barcode_conditional_unique"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="product",
            name="normalized_name_brand_size",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized combination of name, brand, and size for uniqueness.",
                max_length=500,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("normalized_name_brand_size__isnull", False)),
                fields=("normalized_name_brand_size",),
                name="unique_normalized_name_brand_size",
            ),
        ),
    ]
