# Generated by Django 5.2.4 on 2025-11-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0002_remove_product_has_bargain"),
    ]

    operations = [
        migrations.AddField(
            model_name="bargain",
            name="cheaper_store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_cheaper_store",
                to="companies.store",
            ),
        ),
        migrations.AddField(
            model_name="bargain",
            name="expensive_store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_expensive_store",
                to="companies.store",
            ),
        ),
        migrations.AddIndex(
            model_name="bargain",
            index=models.Index(
                fields=["cheaper_store", "expensive_store", "-discount_percentage"],
                name="products_ba_cheaper_95cf94_idx",
            ),
        ),
    ]
