# Generated by Django 5.2.4 on 2025-09-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_price_per_unit_price_string_product_average_rating_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="average_rating",
            new_name="average_user_rating",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="review_count",
            new_name="rating_count",
        ),
    ]
