# Generated by Django 5.2.4 on 2025-10-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_bargain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image_url_pairs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of [company_name, image_url] tuples for this product.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_variations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of normalized name strings for discovered variations.",
            ),
        ),
    ]
