# Generated by Django 5.2.4 on 2025-11-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_price_products_pr_store_i_fcd987_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
