# Generated by Django 5.2.4 on 2025-08-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_store_address_store_city_store_state"),
        ("products", "0003_price_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                help_text="The categories this product belongs to.",
                related_name="products",
                to="companies.category",
            ),
        ),
    ]
