# Generated by Django 5.2.4 on 2025-09-05 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0003_alter_product_substitutes_productsizevariant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="normalized_string_variations",
            new_name="normalized_name_brand_size_variations",
        ),
        migrations.AddField(
            model_name="product",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The normalized version of the product name.",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ProductBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("name_variations", models.JSONField(blank=True, default=list)),
                ("is_store_brand", models.BooleanField(default=False)),
                (
                    "parent_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
