# Generated by Django 5.2.4 on 2025-09-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_plu_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={},
        ),
    ]
