# Generated by Django 5.2.4 on 2025-11-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_delete_popularcategory"),
        ("products", "0003_remove_bargain_super_categories_delete_supercategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="bargain",
            name="primary_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains",
                to="companies.primarycategory",
            ),
        ),
    ]
