# Generated by Django 5.2.4 on 2025-11-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_bargain_cheaper_store_bargain_expensive_store_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="unit_price",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
    ]
