# Generated by Django 5.1.6 on 2025-08-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_normalized_name_brand_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.JSONField(
                default=list,
                help_text="A list of all size-related strings found for the product.",
            ),
        ),
    ]
