# Generated by Django 5.2.4 on 2025-11-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_price_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="scraped_date",
            field=models.DateField(db_index=True),
        ),
    ]
