# Generated by Django 5.2.4 on 2025-08-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="nutritional_information",
        ),
    ]
