# Generated by Django 5.2.4 on 2025-09-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_rename_normalized_string_variations_product_normalized_name_brand_size_variations_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(db_index=True, max_length=12, unique=True)),
                (
                    "is_grouping_prefix",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is this the longest common prefix found? Best for grouping products.",
                    ),
                ),
                (
                    "is_likely_official",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is this our best guess for the official GS1 company prefix?",
                    ),
                ),
                (
                    "product_count",
                    models.IntegerField(
                        default=0,
                        help_text="How many products in our DB share this prefix?",
                    ),
                ),
                (
                    "prefix_length",
                    models.PositiveSmallIntegerField(
                        help_text="The character length of the prefix."
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefixes",
                        to="products.productbrand",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brand Prefixes",
                "ordering": ["brand", "-prefix_length"],
            },
        ),
    ]
