# Generated by Django 5.2.4 on 2025-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_price_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bargain",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The calculated discount percentage ((most_expensive - cheapest) / most_expensive) * 100.",
                null=True,
            ),
        ),
    ]
