# Generated by Django 5.2.4 on 2025-08-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
