# Generated by Django 5.2.4 on 2025-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_delete_popularcategory"),
        ("products", "0004_bargain_primary_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bargain",
            name="primary_category",
        ),
        migrations.AddField(
            model_name="bargain",
            name="primary_categories",
            field=models.ManyToManyField(
                blank=True, related_name="bargains", to="companies.primarycategory"
            ),
        ),
    ]
