# Generated by Django 5.2.4 on 2025-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_bargain_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_bargain",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="A pre-calculated flag indicating if this product is a significant global bargain.",
            ),
        ),
        migrations.DeleteModel(
            name="Bargain",
        ),
    ]
