# Generated by Django 5.2.4 on 2025-11-28 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("products", "0005_alter_price_scraped_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bargain",
            name="cheaper_store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_cheaper_store",
                to="companies.store",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bargain",
            name="expensive_store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_expensive_store",
                to="companies.store",
            ),
            preserve_default=False,
        ),
    ]
