# Generated by Django 5.2.4 on 2025-09-08 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_brandprefix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brandprefix",
            options={},
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="id",
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="is_grouping_prefix",
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="is_likely_official",
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="prefix",
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="prefix_length",
        ),
        migrations.RemoveField(
            model_name="brandprefix",
            name="product_count",
        ),
        migrations.AddField(
            model_name="brandprefix",
            name="brand_name_gs1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brandprefix",
            name="confirmed_official_prefix",
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="brandprefix",
            name="longest_inferred_prefix",
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="brandprefix",
            name="shortest_inferred_prefix",
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="brandprefix",
            name="brand",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="prefix_analysis",
                serialize=False,
                to="products.productbrand",
            ),
        ),
    ]
