# Generated by Django 5.2.4 on 2025-11-13 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0007_delete_popularcategory"),
        ("products", "0005_remove_bargain_primary_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="source",
        ),
        migrations.RemoveField(
            model_name="product",
            name="company_skus",
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="companies.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "sku")},
            },
        ),
    ]
