# Generated by Django 5.2.4 on 2025-11-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_remove_pillarpage_image_path"),
        ("products", "0006_product_has_bargain_delete_bargain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bargain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discount_percentage", models.IntegerField()),
                (
                    "cheaper_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheaper_bargains",
                        to="companies.store",
                    ),
                ),
                (
                    "expensive_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expensive_bargains",
                        to="companies.store",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bargains",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "cheaper_store",
                            "expensive_store",
                            "-discount_percentage",
                        ],
                        name="products_ba_cheaper_95cf94_idx",
                    ),
                    models.Index(
                        fields=["product"], name="products_ba_product_f4abe3_idx"
                    ),
                ],
                "unique_together": {("product", "cheaper_store", "expensive_store")},
            },
        ),
    ]
