# Generated by Django 5.2.4 on 2025-12-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_temp_recreate_bargain_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPriceSummary",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="price_summary",
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "max_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "company_count",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("iga_store_count", models.PositiveIntegerField(default=0)),
                (
                    "best_possible_discount",
                    models.IntegerField(db_index=True, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-best_possible_discount"],
                        name="products_pr_best_po_c10130_idx",
                    ),
                    models.Index(
                        fields=["company_count"], name="products_pr_company_bcf5c8_idx"
                    ),
                ],
            },
        ),
    ]
