# Generated by Django 5.2.4 on 2025-11-26 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_bargain"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bargain",
            name="products_ba_cheaper_95cf94_idx",
        ),
        migrations.RemoveIndex(
            model_name="bargain",
            name="products_ba_product_f4abe3_idx",
        ),
        migrations.AddField(
            model_name="bargain",
            name="cheaper_price",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_cheaper",
                to="products.price",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bargain",
            name="expensive_price",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargains_as_expensive",
                to="products.price",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="bargain",
            unique_together={("product", "cheaper_price", "expensive_price")},
        ),
        migrations.AddIndex(
            model_name="bargain",
            index=models.Index(
                fields=["product", "-discount_percentage"],
                name="products_ba_product_55cb56_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="bargain",
            name="cheaper_store",
        ),
        migrations.RemoveField(
            model_name="bargain",
            name="expensive_store",
        ),
    ]
