# Generated by Django 5.2.4 on 2026-01-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_productpricesummary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bargain",
        ),
    ]
