# Generated by Django 5.2.4 on 2026-06-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_delete_bargain"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category_paths",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Full category paths observed per company. Each entry: {'company': str, 'path': [str], 'path_key': str, 'root_name': str, 'leaf_name': str, 'path_type': str, 'canonical_key': str, 'primary_category_slug': str, 'evidence_count': int}.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="primary_category_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Denormalized list of primary category slugs for fast filtering.",
            ),
        ),
    ]
