# Generated by Django 5.2.4 on 2026-06-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_add_category_paths_and_primary_category_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbrand",
            name="confirmed_official_prefix",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="longest_inferred_prefix",
        ),
    ]
